### ISSUE TITLE
power_state does not take effect when runcmd errors

### ISSUE THREAD

**Issue by ubuntu-server-builder** [canonical/cloud-init#2542]
This bug was originally filed in Launchpad as [LP: #1449318](https://bugs.launchpad.net/cloud-init/+bug/1449318)
<details>
<summary>Launchpad details</summary>
<pre>
affected_projects = ['cloud-init (Ubuntu)', 'cloud-init (Ubuntu Wily)', 'cloud-init (Ubuntu Xenial)']
assignee = smoser
assignee_name = Scott Moser
date_closed = 2016-08-10T14:45:19.828320+00:00
date_created = 2015-04-28T01:12:32.936572+00:00
date_fix_committed = 2016-06-22T13:59:00.203626+00:00
date_fix_released = 2016-08-10T14:45:19.828320+00:00
id = 1449318
importance = high
is_complete = True
lp_url = https://bugs.launchpad.net/cloud-init/+bug/1449318
milestone = None
owner = lrowe
owner_name = Laurence Rowe
private = False
status = fix_released
submitter = lrowe
submitter_name = Laurence Rowe
tags = []
duplicates = []
</pre>
</details>

_Launchpad user **Laurence Rowe(lrowe)** wrote on 2015-04-28T01:12:32.936572+00:00_

When the runcmd errors the power-state-change does not take effect and the instance is not powered off.

AMI ID: ubuntu-vivid-15.04-amd64-server-20150422 (ami-2d10241d)

Instance launched on EC2 using awscli:

$ aws --region us-west-2 ec2 run-instances --image-id ami-2d10241d --instance-type t2.medium --security-groups ssh-http-https --user-data file://fail.cfg

Minimal fail.cfg cloud config:
```
#cloud-config
power_state:
  mode: poweroff

runcmd:
- set -e
- python3 -c "raise Exception"
```

Longer fail.cfg used for retrieving logs:
```
#cloud-config
output:
  all: '| tee -a /var/log/cloud-init-output.log'

power_state:
  mode: poweroff

bootcmd:
- cloud-init-per once ssh-users-ca echo "TrustedUserCAKeys /etc/ssh/users_ca.pub" >> /etc/ssh/sshd_config

runcmd:
- set -e
- python3 -c "raise Exception"

write_files:
- path: /etc/ssh/users_ca.pub
  content: <my ssh ca key>
```
