### ISSUE TITLE
documentation problem regarding user groups

### ISSUE THREAD

**Issue by ubuntu-server-builder** [canonical/cloud-init#2708]
This bug was originally filed in Launchpad as [LP: #1612656](https://bugs.launchpad.net/cloud-init/+bug/1612656)
<details>
<summary>Launchpad details</summary>
<pre>
affected_projects = []
assignee = None
assignee_name = None
date_closed = 2016-08-30T17:56:38.169145+00:00
date_created = 2016-08-12T13:22:56.509063+00:00
date_fix_committed = 2016-08-30T17:56:38.169145+00:00
date_fix_released = 2016-08-30T17:56:38.169145+00:00
id = 1612656
importance = medium
is_complete = True
lp_url = https://bugs.launchpad.net/cloud-init/+bug/1612656
milestone = None
owner = sunil-sunilkchopra
owner_name = Sunil K Chopra
private = False
status = fix_released
submitter = sunil-sunilkchopra
submitter_name = Sunil K Chopra
tags = ['documentation']
duplicates = []
</pre>
</details>

_Launchpad user **Sunil K Chopra(sunil-sunilkchopra)** wrote on 2016-08-12T13:22:56.509063+00:00_

In the latest documentation examples, the first example has an apparent error on line 14.

http://cloudinit.readthedocs.io/en/latest/topics/examples.html

```
# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: foobar
    gecos: Foo B. Bar
    primary-group: foobar
    groups: users
```

It shows that a string is an acceptable value for the `groups` key.  On line 23, it shows another string with comma-separated values.  Both of these values cause errors.  The `groups` key requires an array, even if there is only one value. This is implied at line 109, but not explicitly stated.

Please fix?

thanks!

Sunil
