### ISSUE TITLE
GATEWAY doesn't render VMWare

### ISSUE THREAD

**Issue by ubuntu-server-builder** [canonical/cloud-init#3359]
This bug was originally filed in Launchpad as [LP: #1821216](https://bugs.launchpad.net/cloud-init/+bug/1821216)
<details>
<summary>Launchpad details</summary>
<pre>
affected_projects = []
assignee = None
assignee_name = None
date_closed = 2019-07-28T04:17:44.627154+00:00
date_created = 2019-03-21T18:07:13.413986+00:00
date_fix_committed = None
date_fix_released = None
id = 1821216
importance = medium
is_complete = True
lp_url = https://bugs.launchpad.net/cloud-init/+bug/1821216
milestone = None
owner = john-z
owner_name = John Jelinek
private = False
status = expired
submitter = john-z
submitter_name = John Jelinek
tags = []
duplicates = []
</pre>
</details>

_Launchpad user **John Jelinek(john-z)** wrote on 2019-03-21T18:07:13.413986+00:00_

cloud-init isn't rendered GATEWAY in /etc/sysconfig/network-scripts/ifcfg-eth0 with VMWare:
```
# Created by cloud-init on instance boot automatically, do not edit.
#
BOOTPROTO=none
DEVICE=eth0
IPADDR=172.20.14.192
NETMASK=255.255.255.0
NM_CONTROLLED=no
ONBOOT=yes
TYPE=Ethernet
USERCTL=no
```

Here's the default amazon-linux2 cloud.cfg:
```
users:
 - default

disable_root: true
ssh_pwauth: false

mount_default_fields: [~, ~, 'auto', 'defaults,nofail', '0', '2']
resize_rootfs: noblock
resize_rootfs_tmp: /dev
ssh_deletekeys:   false
ssh_genkeytypes:  ~
syslog_fix_perms: ~

datasource_list: [ NoCloud, AltCloud, ConfigDrive, OVF, None ]
repo_upgrade: security

cloud_init_modules:
 - migrator
 - bootcmd
 - write-files
 - growpart
 - resizefs
 - set-hostname
 - update-hostname
 - update-etc-hosts
 - rsyslog
 - users-groups
 - ssh

cloud_config_modules:
 - mounts
 - locale
 - set-passwords
 - yum-configure
 - yum-add-repo
 - package-update-upgrade-install
 - timezone
 - puppet
 - chef
 - salt-minion
 - mcollective
 - disable-ec2-metadata
 - runcmd

cloud_final_modules:
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - phone-home
 - final-message


system_info:
  default_user:
    name: ec2-user
    lock_passwd: false
    gecos: EC2 Default User
    groups: [wheel, adm, systemd-journal]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
  distro: amazon
  paths:
    cloud_dir: /var/lib/cloud
    templates_dir: /etc/cloud/templates
  ssh_svcname: sshd

chpasswd:
   expire: false


disable_vmware_customization: false
# vim:syntax=yaml
```
