### ISSUE TITLE
autoinstall with nocloud does not seed password when identity is interactive

### ISSUE THREAD

**Issue by ubuntu-server-builder** [canonical/cloud-init#3707]
This bug was originally filed in Launchpad as [LP: #1883180](https://bugs.launchpad.net/cloud-init/+bug/1883180)
<details>
<summary>Launchpad details</summary>
<pre>
affected_projects = ['subiquity']
assignee = None
assignee_name = None
date_closed = 2020-06-15T11:06:57.191161+00:00
date_created = 2020-06-11T21:45:30.096727+00:00
date_fix_committed = None
date_fix_released = None
id = 1883180
importance = undecided
is_complete = True
lp_url = https://bugs.launchpad.net/cloud-init/+bug/1883180
milestone = None
owner = tylerecouture
owner_name = tylerecouture
private = False
status = invalid
submitter = tylerecouture
submitter_name = tylerecouture
tags = ['medium', 'nocloud']
duplicates = [1959833]
</pre>
</details>

_Launchpad user **tylerecouture(tylerecouture)** wrote on 2020-06-11T21:45:30.096727+00:00_

I am using the [autoinstall process](https://ubuntu.com/server/docs/install/autoinstall) with nocloud provider.  I want to manually enter the hostname, so have set the identity section to interactive.  However, when I do this, the password section is blank instead of pre-seeded with the value provided.  The other identity sections (hostname, username, realname) are preseeded as expected, when the interactive section comes up.  Only the pw is missing.

1. Tell us your cloud provider: `ds=nocloud-net`
2. Any appropriate cloud-init configuration you can provide us:

*user-data*
```
#cloud-config
autoinstall:
  version: 1
  interactive-sections:
    - identity
  identity:
    hostname: change-me
    password: $6$xnH...
    username: admin
    realname: Admin
```
