### ISSUE TITLE
example config for chef uses wrong syntax

### ISSUE THREAD

**Issue by ubuntu-server-builder** [canonical/cloud-init#3776]
This bug was originally filed in Launchpad as [LP: #1892947](https://bugs.launchpad.net/cloud-init/+bug/1892947)
<details>
<summary>Launchpad details</summary>
<pre>
affected_projects = []
assignee = None
assignee_name = None
date_closed = 2020-08-26T20:05:53.776139+00:00
date_created = 2020-08-25T23:07:23.452620+00:00
date_fix_committed = 2020-08-26T20:05:53.776139+00:00
date_fix_released = 2020-08-26T20:05:53.776139+00:00
id = 1892947
importance = undecided
is_complete = True
lp_url = https://bugs.launchpad.net/cloud-init/+bug/1892947
milestone = None
owner = ananke
owner_name = ananke
private = False
status = fix_released
submitter = ananke
submitter_name = ananke
tags = []
duplicates = []
</pre>
</details>

_Launchpad user **ananke(ananke)** wrote on 2020-08-25T23:07:23.452620+00:00_

The example configuration https://cloudinit.readthedocs.io/en/latest/topics/examples.html#install-and-run-chef-recipes has a missing YAML key:

```
# Key from https://packages.chef.io/chef.asc
apt:
  sources:
    source1: "deb http://packages.chef.io/repos/apt/stable $RELEASE main"
    key: |
```

Should be instead:

```
# Key from https://packages.chef.io/chef.asc
apt:
  sources:
    source1: 
      source: "deb http://packages.chef.io/repos/apt/stable $RELEASE main"
      key: |
``

Cheers!
