### ISSUE TITLE
cloudconfig not writing maas data source

### ISSUE THREAD

**Issue by ubuntu-server-builder** [canonical/cloud-init#3873]
This bug was originally filed in Launchpad as [LP: #1927020](https://bugs.launchpad.net/cloud-init/+bug/1927020)
<details>
<summary>Launchpad details</summary>
<pre>
affected_projects = ['curtin']
assignee = None
assignee_name = None
date_closed = 2021-05-13T15:26:52.382276+00:00
date_created = 2021-05-03T22:29:27.716874+00:00
date_fix_committed = None
date_fix_released = None
id = 1927020
importance = undecided
is_complete = True
lp_url = https://bugs.launchpad.net/cloud-init/+bug/1927020
milestone = None
owner = cbnorman
owner_name = Chris Norman
private = False
status = invalid
submitter = cbnorman
submitter_name = Chris Norman
tags = []
duplicates = []
</pre>
</details>

_Launchpad user **Chris Norman(cbnorman)** wrote on 2021-05-03T22:29:27.716874+00:00_

further background https://discourse.maas.io/t/debian10-fails-on-final-reboot/4486

I'm deploying a debian 10 buster image using MAAS. No errors are reported in MAAS or curtin install but on the final boot cloud-init reports `Failed to load metadata and userdata`. checking the config for the machine in maas shows all the cloudconfig: to connect to maas but the files with oauth credentials etc dont seem to have been copied to the target.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **James Falcon(falcojr)** wrote on 2021-05-05T14:02:29.931267+00:00_

Looking at the logs, a few things stand out:
 * /etc/cloud/cloud.cfg is practically empty. This is usually baked into the image, so to me this suggests a problem happening before we get to cloud-init.
 * ds-identify.log shows it couldn't detect a datasource. This means this check returned false, but it should be returning true on MAAS (https://github.com/canonical/cloud-init/blob/master/tools/ds-identify#L784).
 * The cloud-init code could also not detect a datasource. This again seems to suggest a problem with the image or fabric itself, not cloud-init.

I'm going to set the state of this bug to Incomplete for now. If you can provide more information to show that cloud-init isn't doing what you expected, feel free to set the status back to New.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Scott Moser(smoser)** wrote on 2021-05-05T15:37:29.548163+00:00_

When I  looked at this, the most obvious thing to me was that curtin did not write a file in /etc/cloud/cloud.cfg.d/ that configured the MAAS datasource.

A quick look at curtin didn't remind me how that file gets written in ubuntu. 
 https://github.com/canonical/curtin/blob/204728a21d1b0a6733a4f229d759b9ab324d9258/curtin/commands/curthooks.py#L1464

The 'cloud-config' entries provided by MAAS (https://discourse.maas.io/t/debian10-fails-on-final-reboot/4486/5) should then get written into /etc/cloud/cloud.cfg.d/ . If they aren't written, then the installed system won't recognize it is configured for maas.

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Chris Norman(cbnorman)** wrote on 2021-05-06T10:09:44.048821+00:00_

thanks for looking into this and agreed the root problem seems to be the files are not written by curtin. I dont see any errors in the curtin log, do you know why that handle_cloudconfig function would not be run?

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Ryan Harper(raharper)** wrote on 2021-05-06T15:50:34+00:00_

On Thu, May 6, 2021 at 5:15 AM Chris Norman <1927020@bugs.launchpad.net>
wrote:

> thanks for looking into this and agreed the root problem seems to be the
> files are not written by curtin. I dont see any errors in the curtin
> log, do you know why that handle_cloudconfig function would not be run?
>

MAAS sends this information through the debconf_selections curtin config:

https://curtin.readthedocs.io/en/latest/topics/config.html#debconf-selections

And the Ubuntu cloud-init package has a postinst which parses these
values and writes them out:

https://github.com/canonical/cloud-init/blob/ubuntu/daily/devel/debian/cloud-init.postinst#L54



> --
> You received this bug notification because you are subscribed to cloud-
> init.
> https://bugs.launchpad.net/bugs/1927020
>
> Title:
>   cloudconfig not writing maas data source
>
> To manage notifications about this bug go to:
> https://bugs.launchpad.net/cloud-init/+bug/1927020/+subscriptions
>

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Lee Trager(ltrager)** wrote on 2021-05-11T20:51:23.022469+00:00_

As per discourse it looks like the bug is in Curtin. /etc/cloud/cloud.cfg.d/90_dpkg_maas.cfg is written then deleted by Curtin.

Applying debconf selections
Running command ['unshare', '--fork', '--pid', '--', 'chroot', '/tmp/tmpihv32ogj/target', 'debconf-set-selections'] with allowed return codes [0] (capture=True)
Running command ['unshare', '--fork', '--pid', '--', 'chroot', '/tmp/tmpihv32ogj/target', 'dpkg-query', '--list'] with allowed return codes [0] (capture=True)
unconfiguring cloud-init
cleaning cloud-init config from: ['/tmp/tmpihv32ogj/target/etc/cloud/cloud.cfg.d/90_dpkg_local_cloud_config.cfg', '/tmp/tmpihv32ogj/target/etc/cloud/cloud.cfg.d/90_dpkg_maas.cfg', '/tmp/tmpihv32ogj/target/etc/cloud/cloud.cfg.d/90_dpkg.cfg']

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Ryan Harper(raharper)** wrote on 2021-05-11T22:31:53.400624+00:00_

> As per discourse it looks like the bug is in Curtin.

No

The point of removing any files in /etc/cloud/cloud.cfg.d is that dpkg-reconfigure *WILL* write out whatever values it needs from the debconf_selections.

So the two questions are:

1) in the maas config sent to this image does it include debconf_selections (I assume yes)
2) does the cloud-init package in the target filesystem include the cloudinit.postinstall from upstream cloud-init which handles the maas preseed ?

**Comment by ubuntu-server-builder** [comment]
_Launchpad user **Chris Norman(cbnorman)** wrote on 2021-05-11T23:01:42.102051+00:00_

i believe the maas config is sent to the image. here is the output from the maas server:

```
#maas admin machine get-curtin-config ykfy3r 
Success.
Machine-readable output follows:
apt:
  preserve_sources_list: false
  proxy: http://192.168.50.10:8000/
  sources_list: 'deb http://deb.debian.org/debian buster main

    deb-src http://deb.debian.org/debian buster main

    deb http://security.debian.org/debian-security buster/updates main

    deb-src http://security.debian.org/debian-security buster/updates main

    '
cloudconfig:
  maas-cloud-config:
    content: "#cloud-config\ndatasource:\n  MAAS:\n    consumer_key: X7HqXFtzruufCcfjnF\n\
      \    metadata_url: http://localhost:5240/MAAS/metadata/\n    token_key: M7VUBVr5KQwgVH3QZZ\n\
      \    token_secret: 8tJ8wUJNp6HxKSEtMwA8YyYtFzhpkGHL\n"
    path: /etc/cloud/cloud.cfg.d/90_maas_cloud_config.cfg
  maas-datasource:
    content: 'datasource_list: [ MAAS ]'
    path: /etc/cloud/cloud.cfg.d/90_maas_datasource.cfg
  maas-reporting:
    content: "#cloud-config\nreporting:\n  maas:\n    consumer_key: X7HqXFtzruufCcfjnF\n\
      \    endpoint: http://localhost:5240/MAAS/metadata/status/ykfy3r\n    token_key:\
      \ M7VUBVr5KQwgVH3QZZ\n    token_secret: 8tJ8wUJNp6HxKSEtMwA8YyYtFzhpkGHL\n \
      \   type: webhook\n"
    path: /etc/cloud/cloud.cfg.d/90_maas_cloud_init_reporting.cfg
  maas-ubuntu-sso:
    content: "#cloud-config\nsnappy:\n  email: admin@admin.com\n"
    path: /etc/cloud/cloud.cfg.d/90_maas_ubuntu_sso.cfg
debconf_selections:
  grub2: grub2   grub2/update_nvram  boolean false
  maas: 'cloud-init   cloud-init/datasources  multiselect MAAS

    cloud-init   cloud-init/maas-metadata-url  string http://localhost:5240/MAAS/metadata/

    cloud-init   cloud-init/maas-metadata-credentials  string oauth_consumer_key=X7HqXFtzruufCcfjnF&oauth_token_key=M7VUBVr5KQwgVH3QZZ&oauth_token_secret=8tJ8wUJNp6HxKSEtMwA8YyYtFzhpkGHL

    cloud-init   cloud-init/local-cloud-config  string manage_etc_hosts: true\nmanual_cache_clean:
    true\nreporting:\n  maas:\n    consumer_key: X7HqXFtzruufCcfjnF\n    endpoint:
    http://localhost:5240/MAAS/metadata/status/ykfy3r\n    token_key: M7VUBVr5KQwgVH3QZZ\n    token_secret:
    8tJ8wUJNp6HxKSEtMwA8YyYtFzhpkGHL\n    type: webhook\n

    '
install:
  error_tarfile: /tmp/curtin-logs.tar
  log_file: /tmp/install.log
  post_files:
  - /tmp/install.log
  - /tmp/curtin-logs.tar
kernel:
  fallback-package: linux-image-amd64
  package: linux-image-amd64
late_commands:
  datasource:
  - curtin
  - in-target
  - --
  - sh
  - -c
  - 'echo "datasource_list: [ MAAS ]" > /etc/cloud/cloud.cfg.d/90_dpkg.cfg'
  maas:
  - wget
  - --no-proxy
  - http://localhost:5240/MAAS/metadata/latest/by-id/ykfy3r/
  - --post-data
  - op=netboot_off
  - -O
  - /dev/null
network:
  config:
  - id: ens33
    mac_address: 00:0c:29:d7:99:89
    mtu: 1500
    name: ens33
    subnets:
    - address: 192.168.50.34/24
      dns_nameservers:
      - 192.168.50.10
      - 8.8.8.8
      dns_search: &id001
      - maas
      type: static
    type: physical
  - address:
    - 192.168.50.10
    search: *id001
    type: nameserver
  version: 1
network_commands:
  builtin:
  - curtin
  - net-meta
  - custom
partitioning_commands:
  builtin:
  - curtin
  - block-meta
  - custom
reporting:
  maas:
    consumer_key: X7HqXFtzruufCcfjnF
    endpoint: http://localhost:5240/MAAS/metadata/status/ykfy3r
    token_key: M7VUBVr5KQwgVH3QZZ
    token_secret: 8tJ8wUJNp6HxKSEtMwA8YyYtFzhpkGHL
    type: webhook
showtrace: true
storage:
  config:
  - grub_device: true
    id: sda
    name: sda
    path: /dev/sda
    ptable: gpt
    type: disk
    wipe: superblock
  - device: sda
    flag: bios_grub
    id: sda-part1
    number: 1
    offset: 4194304B
    size: 1048576B
    type: partition
    wipe: zero
  - device: sda
    flag: boot
    id: sda-part2
    name: sda-part2
    number: 2
    size: 536870912B
    type: partition
    uuid: 09527817-1706-415d-9c5e-b0b4aafdfe8f
    wipe: superblock
  - device: sda
    id: sda-part3
    name: sda-part3
    number: 3
    size: 20929576960B
    type: partition
    uuid: 6408531a-4fed-44d5-a7b0-9494e11c4ecb
    wipe: superblock
  - fstype: fat32
    id: sda-part2_format
    label: efi
    type: format
    uuid: c57cc8ab-50db-4345-b07d-6d3024e29a43
    volume: sda-part2
  - fstype: ext4
    id: sda-part3_format
    label: root
    type: format
    uuid: 06244900-d7a9-455a-a167-40845148af3c
    volume: sda-part3
  - device: sda-part3_format
    id: sda-part3_mount
    path: /
    type: mount
  - device: sda-part2_format
    id: sda-part2_mount
    path: /boot/efi
    type: mount
  version: 1
verbosity: 3
write_files:
  userconfig:
    content: "groups:\n  - docker\nusers:\n  - default\n  - name: buster\n    gecos:\
      \ Service Operator\n    primary_group: myuser\n    groups: [docker,sudo]\n \
      \   lock_passwd: false\n    sudo: ALL=(ALL) NOPASSWD:ALL\n    plain_text_passwd:\
      \ buster\n    shell: /bin/bash\n    ssh_authorized_keys:\n      - ecdsa-sha2-nistp521\
      \ AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADGl/XFwwwDam1MoyQ3vmfJxaJVRx8ut7uOliGeUt/WzPytO2sx2QRsKxLt/tPnRbj4gJIMH2vhM0QwB1FEsribSAGOwd0bQuCGSpN9Vh+wPsp7xVoiOB5MWDgQGagmSY6XubnWP0pVfUd+78dJLg9ZDAHXOJlVzGHJX8jeslpJo3MIbw==\
      \ chrisnorman@C02XC3C7JG5L\n"
    path: /etc/cloud/cloud.cfg.d/00-users.cfg
```

if i trap the ephemeral boot image (ubuntu). cd into /curtin and run /var/lib/cloud/instance/scripts/part-001 it outputs:
```
./bin/curtin --install-deps install   --config=configs/config-000.cfg --config=configs/config-001.cfg   --config=configs/config-002.cfg --config=configs/config-003.cfg   --config=configs/config-004.cfg --config=configs/config-005.cfg --config=configs/config-006.cfg http://192.168.50.10:5248/images/custom/amd64/generic/debian1080/uploaded/root-tgz
```
In the /curtin/config/* files i can see the config from get-curtin-config.

how can i confirm cloudinit.postinstall exists in the target image?
