### ISSUE TITLE
dhcp lookups depend on end-of-life dhclient

### ISSUE THREAD

**Issue by ubuntu-server-builder** [canonical/cloud-init#4077]
This bug was originally filed in Launchpad as [LP: #2006784](https://bugs.launchpad.net/cloud-init/+bug/2006784)
<details>
<summary>Launchpad details</summary>
<pre>
affected_projects = []
assignee = None
assignee_name = None
date_closed = 2023-02-10T17:17:28.104802+00:00
date_created = 2023-02-09T21:28:52.364112+00:00
date_fix_committed = None
date_fix_released = None
id = 2006784
importance = undecided
is_complete = True
lp_url = https://bugs.launchpad.net/cloud-init/+bug/2006784
milestone = None
owner = imsofi
owner_name = Sofi
private = False
status = invalid
submitter = imsofi
submitter_name = Sofi
tags = []
duplicates = []
</pre>
</details>

_Launchpad user **Sofi(imsofi)** wrote on 2023-02-09T21:28:52.364112+00:00_

When using DataSourceHetzner, there is a required dhcp lookup. This digs down to a function named `maybe_perform_dhcp_discovery` which breaks when a `which dhclient` does not return a binary. This raises a `NoDHCPLeaseMissingDhclientError`.

I have only tested this under NixOS, as its one of the first distributions to have have removed `dhclient` from its the package tree following the deprecation by ISC's to the package.

DHCP lookups should be changed to support a non-deprecated dhcp library.

Cloud-provider: Hetzner

Cloud-init config:

```
system_info:
  distro: nixos
  network:
    renderers: [networkd]
users:
 - root

disable_root: false
preserve_hostname: false

cloud_init_modules:
 - set_hostname
 - update_hostname
 - update_etc_hosts
cloud_config_modules: []
cloud_final_modules: []

datasource_list:
 - DataSourceHetzner
```

Source where error is raised from:
https://github.com/canonical/cloud-init/blob/b3978cbd6c68c883f5ab02630d8d7fcb220b270c/cloudinit/net/dhcp.py#L69

End-of-life notice from ISC at 02 Jul 2021:
https://www.isc.org/blogs/dhcp-client-relay-eom/
