### ISSUE TITLE
cloud init 23.1.2 fails since this week on AWS, DigitalOcean and ExoScale

### ISSUE THREAD

**Issue by boaks** [canonical/cloud-init#4117]
A cloud-init fails since this week. It has still been working last week.

[cloud-config-dev.yaml](https://github.com/boaks/californium/blob/add_cloud_demo_server/demo-apps/cf-cloud-demo-server/service/cloud-installs/cloud-config-dev.yaml)

```
package_upgrade: true

packages:
# java - runtime for java application
 - openjdk-17-jre-headless
# fail2ban - network protection 
 - fail2ban

snap:
  commands:
   - snap refresh
# public x509 certificate / letsencrypt 
   - snap install --classic certbot

disable_root: false

users:
 - name: cali
   gecos: (Cf) Californium Demo Server
   lock_passwd: true
```

AWS, Ubuntu 20.04.6 LTS, cloud-init  23.1.2-0ubuntu0~20.04.1

>  finish: modules-final: FAIL: running modules for final

Same on DigitalOcean and ExoScale. Also on retry. Yesterday and today.

(If required, I may upload the "collect-logs", but I'm not sure, if that leaks credentials.)
