### ISSUE TITLE
Resizefs for none-root partition

### ISSUE THREAD

**Issue by mak241265** [canonical/cloud-init#4147]
# Enhancement
Currently iam trying to use cloud image ubuntu 22.04 for our production services.i thought we would be able to resize all of partitions as well as root and none root by cloud init. so we set the below configs:

```yaml
growpart:
  mode: growpart
  devices: ['/','/home','/var']
  ignore_growroot_disabled: true
```

but we found out that Resizefs only used for root partition.
would be great if it lets us to use resizefs for non root partition as well
