### ISSUE TITLE
Metric value not being assigned to the routes in V2 networking configuration

### ISSUE THREAD

**Issue by yapancha** [canonical/cloud-init#4217]
# Bug report
While providing a V2 networking configuration that contains routes and their metric, the rendered networkd configuration is missing the metric values for each route.

## Steps to reproduce the problem
For the given v2 configuration
```
network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - 192.168.1.10/24
      gateway4: 192.168.1.1
      routes:
        - to: 10.0.0.0/8
          via: 192.168.1.2
          metric: 100
        - to: 172.16.0.0/16
          via: 192.168.1.3
          metric: 200
        - to: 192.168.2.0/24
          via: 192.168.1.4
          metric: 300
```
The generated networkd configuration looks like
```
[Match]
Name=eth0

[Network]
Address=192.168.1.10/24
Gateway=192.168.1.1

[Route]
Destination=10.0.0.0/8
Gateway=192.168.1.2

[Route]
Destination=172.16.0.0/16
Gateway=192.168.1.3

[Route]
Destination=192.168.2.0/24
Gateway=192.168.1.4
```

VS the expected networkd configuration
```
[Match]
Name=eth0

[Network]
Address=192.168.1.10/24
Gateway=192.168.1.1

[Route]
Destination=10.0.0.0/8
Gateway=192.168.1.2
Metric=100

[Route]
Destination=172.16.0.0/16
Gateway=192.168.1.3
Metric=200

[Route]
Destination=192.168.2.0/24
Gateway=192.168.1.4
Metric=300
```

## Environment details
- Cloud-init version: >= 22.4
- Operating System Distribution: Ubuntu
- Cloud provider, platform or installer type: N/A

## Additional information
- seems like an issue with `_v2_to_v1_ipcfg` function. 
- While calling `_normalize_route` function, it is not adding the metric value
```Python
        routes = []
        for route in cfg.get("routes", []):
            routes.append(
                _normalize_route(
                    {
                        "destination": route.get("to"),
                        "gateway": route.get("via"),
                        # "metric": route.get("metric"), # this value should be supplied if exists
                    }
                )
            )
```
