### ISSUE TITLE
[enhancement]: network-config via nocloud-net with custom webserver

### ISSUE THREAD

**Issue by codefritzel** [canonical/cloud-init#4303]
# Enhancement
Why can't I specify the network-config using this method?
If a drive is mounted with the network-config file, this works. 

Is there any reason why the custom webserver method (nocloud-net) this not support?

See https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html

**Comment by dermotbradley** [comment]
> Why can't I specify the network-config using this method?

You can.

Yes nocloud-net does not request a "network-config" url. I do not know the reasons for this.

However, as indicated in the document you linked to, you **can** embed network configuration in the meta-data.

To quote from that document:

```
Also, you can inject an /etc/network/interfaces file by providing the content for that file in the network-interfaces field of meta-data.
```

and immediately after this quote the document provides an example of doing so.

**Comment by TheRealFalcon** [comment]
@codefritzel Does embedding network into meta data work for your use cases? Was there a reason you wanted a separate request for network-config, or just not aware that it could be done this way?

**Comment by codefritzel** [comment]
Thanks for the hint with the `network-interfaces` field but it does not work for my case.

My web server provides the following meta_data:
```
instance-id: instance1
local-hostname: instance1
network-interfaces:
  network:
    ethernets:
      interface0:
        addresses:
        - 40.156.170.15/24
        gateway4: 40.156.170.1
        match:
          macaddress: '52:54:00:12:34:56'
        set-name: interface0
    version: 2
```
The hostname is applied, but the network configuration is not.

If I add the network section to /etc/cloud.cfg.d/ is works.
