### ISSUE TITLE
Rebooting VM during packer build causes cloud-init to run instance modules again

### ISSUE THREAD

**Issue by shaneholder** [canonical/cloud-init#4359]
# Bug report
I am attempting to use Packer to create a golden image that mounts /var as a partition.  In the Packer build data is copied from several folders to the mounted *alt_* folders and then a sed command is executed against fstab to replace the /alt_ with a blank to make the real mount points.  The VM is then rebooted before continuing with the rest of the golden image configuration, however after the boot the changes made to fstab are replace by cloud-init.  Log files are attached.

Packer build section
``` 
build {
  sources = ["source.azure-arm.linux-image"]

  provisioner "file" {
    source = "${local.scripts_folder}/100_golden.cfg"
    destination = "/tmp/"
  }

  provisioner "shell" {
    inline = ["sudo mv /tmp/100_golden.cfg /etc/cloud/cloud.cfg.d/"]
  }

  # copy var to /alt_var
  provisioner "shell" {
    inline = [
      "sudo sh -c 'cd /var/; tar cf - . | (cd /alt_var; tar xf -)'",
      "sudo sh -c 'cd /home/; tar cf - . | (cd /alt_home; tar xf -)'",
      "sudo sh -c 'cd /tmp/; tar cf - . | (cd /alt_tmp; tar xf -)'"      
    ]
  }

  # reboot vm to mount /var
  provisioner "shell" {
    inline = [
      "sudo sed -i 's#/alt_#/#' /etc/fstab",
    ]
  }

  # reboot vm to mount /var
  provisioner "shell" {
    inline = [
      "sudo reboot"
    ]
    expect_disconnect = true
    pause_after = "60s"
  }
}
```

Cloud Config
``` 
#cloud-config

disk_setup:
  /dev/disk/azure/scsi1/lun0:
    table_type: gpt
    layout: 
      - 15
      - 14
      - 28
      - 14
      - 14
      - 14
    overwrite: True

fs_setup:
  - device: /dev/disk/azure/scsi1/lun0
    partition: 1
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 2
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 3
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 4
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 5
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 6
    filesystem: ext4

mounts:
 - [ "/dev/disk/azure/scsi1/lun0-part1", "/alt_home", "auto", "defaults,nofail", "0", "2" ]
 - [ "/dev/disk/azure/scsi1/lun0-part2", "/alt_tmp", "auto", "defaults,nofail", "0", "2" ]
 - [ "/dev/disk/azure/scsi1/lun0-part3", "/alt_var", "auto", "defaults,nofail", "0", "2" ]
 - [ "/dev/disk/azure/scsi1/lun0-part4", "/alt_var/log", "auto", "defaults,nofail,x-mount.mkdir", "0", "2" ]
 - [ "/dev/disk/azure/scsi1/lun0-part5", "/alt_var/log/audit", "auto", "defaults,nofail,x-mount.mkdir", "0", "2" ]
 - [ "/dev/disk/azure/scsi1/lun0-part6", "/alt_var/tmp", "auto", "defaults,nofail,x-mount.mkdir", "0", "2" ]
```
## Environment details
- Cloud-init version: 
/usr/bin/cloud-init 23.2.2-0ubuntu0~20.04.1
- Operating System Distribution: 
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
- Cloud provider, platform or installer type:
Azure

## cloud-init logs
[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/12362093/cloud-init.tar.gz)

**Comment by shaneholder** [comment]
Adding the fstab in question.
```
# CLOUD_IMG: This file was created/modified by the Cloud Image build process
UUID=10657b0e-bcdb-4859-aeaf-31f0fb6dbde6       /        ext4   defaults,discard        0 1
UUID=CD18-78B8  /boot/efi       vfat    umask=0077      0 1
/dev/disk/azure/scsi1/lun0-part1        /alt_home       auto    defaults,nofail,comment=cloudconfig     0       2
/dev/disk/azure/scsi1/lun0-part2        /alt_tmp        auto    defaults,nofail,comment=cloudconfig     0       2
/dev/disk/azure/scsi1/lun0-part3        /alt_var        auto    defaults,nofail,comment=cloudconfig     0       2
/dev/disk/azure/scsi1/lun0-part4        /alt_var/log    auto    defaults,nofail,x-mount.mkdir,comment=cloudconfig       0       2
/dev/disk/azure/scsi1/lun0-part5        /alt_var/log/audit      auto    defaults,nofail,x-mount.mkdir,comment=cloudconfig       0       2
/dev/disk/azure/scsi1/lun0-part6        /alt_var/tmp    auto    defaults,nofail,x-mount.mkdir,comment=cloudconfig       0       2
/dev/disk/cloud/azure_resource-part1    /mnt    auto    defaults,nofail,x-systemd.requires=cloud-init.service,_netdev,comment=cloudconfig       0       2
```

**Comment by igalic** [comment]
you could `touch /etc/cloud/cloud-init.disabled` before packer reboot, and remove it afterwards

**Comment by shaneholder** [comment]
> you could `touch /etc/cloud/cloud-init.disabled` before packer reboot, and remove it afterwards

Thanks for the idea but cloud init still ran after the reboot..srsly odd.

**Comment by aciba90** [comment]
> Thanks for the idea but cloud init still ran after the reboot..srsly odd.

That's weird. Are we sure the file is being created before rebooting? Could you please attach the logs of your run touching `cloud-init.disabled`?

I believe the reason for cloud-init fully running after the reboot is because the packer config moves [/var/lib/cloud/](https://cloudinit.readthedocs.io/en/latest/development/dir_layout.html#directory-layout), which contains the cloud-init state of the first run.
If we want cloud-init to run modules that run on every boot and, we should transfer somehow `/alt_var/lib/cloud/` to `/var/lib/cloud`.

Another option would be to have two config files. `100_golden.cfg` as-is and a supplemental `101_final.cfg` containing the `mounts` config without `alt`., then remove `100_golden.cfg` before reboot using packer or [runcmd](https://cloudinit.readthedocs.io/en/latest/reference/modules.html#runcmd), please note that without restoring `/var/lib/cloud`, cloud-init would treat this as a first boot.

In any case, I believe this is not a cloud-init issue.

**Comment by shaneholder** [comment]
@aciba90 thanks for the reply.  I assume you're referring to my var manipulation in packer.  I tried several configurations even one where i don't manipulate /var thinking something along the same lines as you but I still get the same behavior.  While working this weekend I also discovered that I needed to wait for cloud init to complete using `cloud-init status --wait`.  Even with that it seems that cloud-init is re-running.  I've attached new logs and updated configuration files here.

Packer config
```
locals {
  scripts_folder = "${path.cwd}/Linux/scripts"
  compliance_folder = "${path.cwd}/compliance/ubuntu2004"
  cwd = "${path.cwd}"
  oscap_profiles = ["stig", "cis_level1_server"]
}

source "azure-arm" "linux-image" {
  azure_tags = {
    OS = var.OS
    Version = var.OS_version
  }
  use_azure_cli_auth  = true
  image_offer         = var.image_offer
  image_publisher     = var.image_publisher
  image_sku           = var.image_sku
  shared_image_gallery_destination {
    subscription          = var.subscription_id
    resource_group        = var.sig_rg_name
    gallery_name          = var.gallery_name
    image_name            = var.image_name
    image_version         = var.image_version
    replication_regions   = var.replication_regions
    storage_account_type  = var.storage_account_type
  } 
  build_resource_group_name               = var.packer_rg_name
  virtual_network_name                    = var.vnet_name
  virtual_network_subnet_name             = var.subnet_name
  virtual_network_resource_group_name     = var.vnet_rg_name
  private_virtual_network_with_public_ip  = true
  managed_image_name                      = "${var.image_name}-${var.image_version}"
  managed_image_resource_group_name       = var.image_rg_name
  os_type                                 = var.os_type
  vm_size                                 = var.vm_size
  disk_additional_size                    = [35] #/home(5) /tmp(5) /var(10) /var/log(5) /var/log/audit(5) /var/tmp(5)
  custom_data_file                        = "${local.scripts_folder}/cloud.cfg"
  ssh_private_key_file                    = "~/.ssh/id_rsa"
}

build {
  sources = ["source.azure-arm.linux-image"]
  
  # Wait for cloud init to complete
  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [
      "cloud-init status --wait"
    ]
  }


  # copy var to /alt_var
  provisioner "shell" {
    remote_folder = "/home/packer"
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [       
      "cd /home/; tar --selinux --acls --xattrs -cf - . | (cd /alt_home; tar xf -)"
    ]
  }

  # reboot vm to mount /var
  provisioner "shell" {
    remote_folder = "/home/packer"
    inline = [
      "sudo sed -i 's#/alt_#/#' /etc/fstab",
    ]
  }

  provisioner "breakpoint" {
    disable = false
    note    = "reboot next"
  }

  # reboot vm to mount /var
  provisioner "shell" {
    remote_folder = "/home/packer"
    inline = [
      "sudo reboot"
    ]
    expect_disconnect = true
    pause_after = "60s"
  }

  provisioner "breakpoint" {
    disable = false
    note    = "post reboot"
  }
}
```

cloud-init config
```
#cloud-config

disk_setup:
  /dev/disk/azure/scsi1/lun0:
    table_type: gpt
    layout: 
      - 15
      - 14
      - 28
      - 14
      - 14
      - 14
    overwrite: True

fs_setup:
  - device: /dev/disk/azure/scsi1/lun0
    partition: 1
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 2
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 3
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 4
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 5
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 6
    filesystem: ext4

# disable ipv6
# disable/remove iptables?
# accounts?
# Matthew Matkin Quest agent licencing?  RHEL/SLES

mounts:
 - [ "/dev/disk/azure/scsi1/lun0-part1", "/alt_home", "auto", "defaults,nofail", "0", "2" ]
#  - [ "/dev/disk/azure/scsi1/lun0-part2", "/alt_tmp", "auto", "defaults,nofail,mode=1777", "0", "2" ]
#  - [ "/dev/disk/azure/scsi1/lun0-part3", "/alt_var", "auto", "defaults,nofail", "0", "2" ]
#  - [ "/dev/disk/azure/scsi1/lun0-part4", "/alt_var/log", "auto", "defaults,nofail,x-mount.mkdir", "0", "2" ]
#  - [ "/dev/disk/azure/scsi1/lun0-part5", "/alt_var/log/audit", "auto", "defaults,nofail,x-mount.mkdir", "0", "2" ]
#  - [ "/dev/disk/azure/scsi1/lun0-part6", "/alt_var/tmp", "auto", "defaults,nofail,x-mount.mkdir", "0", "2" ]

package_update: true

packages:
 - vim
 - less
 - libopenscap8
 - zsh
 - netcat
 - bind9-dnsutils
 - dos2unix
 - lsof
 - traceroute
 - tmux
 - tree
 - aide
 - postfix

```

[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/12396593/cloud-init.tar.gz)

**Comment by shaneholder** [comment]
@aciba90 thanks for the reply.  I assume you're referring to my var manipulation in packer.  I tried several configurations even one where i don't manipulate /var thinking something along the same lines as you but I still get the same behavior.  While working this weekend I also discovered that I needed to wait for cloud init to complete using `cloud-init status --wait`.  Even with that it seems that cloud-init is re-running.  I've attached new logs and updated configuration files here.

Note the line in the cloud-init.log
2023-08-21 13:38:55,813 - cc_mounts.py[DEBUG]: Changes to fstab: ['- /dev/disk/azure/scsi1/lun0-part1 /home auto defaults,nofail,comment=cloudconfig 0 2', '+ /dev/disk/azure/scsi1/lun0-part1 /alt_home auto defaults,nofail,comment=cloudconfig 0 2']

[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/12396903/cloud-init.tar.gz)

Packer config
```

locals {
  scripts_folder = "${path.cwd}/Linux/scripts"
  compliance_folder = "${path.cwd}/compliance/ubuntu2004"
}

source "azure-arm" "linux-image" {
  azure_tags = {
    OS = var.OS
    Version = var.OS_version
  }
  use_azure_cli_auth  = true
  image_offer         = var.image_offer
  image_publisher     = var.image_publisher
  image_sku           = var.image_sku
  shared_image_gallery_destination {
    subscription          = var.subscription_id
    resource_group        = var.sig_rg_name
    gallery_name          = var.gallery_name
    image_name            = var.image_name
    image_version         = var.image_version
    replication_regions   = var.replication_regions
    storage_account_type  = var.storage_account_type
  } 
  build_resource_group_name               = var.packer_rg_name
  virtual_network_name                    = var.vnet_name
  virtual_network_subnet_name             = var.subnet_name
  virtual_network_resource_group_name     = var.vnet_rg_name
  private_virtual_network_with_public_ip  = true
  managed_image_name                      = "${var.image_name}-${var.image_version}"
  managed_image_resource_group_name       = var.image_rg_name
  os_type                                 = var.os_type
  vm_size                                 = var.vm_size
  disk_additional_size                    = [35] #/home(5) /tmp(5) /var(10) /var/log(5) /var/log/audit(5) /var/tmp(5)
  custom_data_file                        = "${local.scripts_folder}/cloud.cfg"
  ssh_private_key_file                    = "~/.ssh/id_rsa"
}

build {
  sources = ["source.azure-arm.linux-image"]
  
  # Wait for cloud init to complete
  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [
      "cloud-init status --wait"
    ]
  }


  # copy var to /alt_var
  provisioner "shell" {
    remote_folder = "/home/packer"
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline = [       
      "cd /home/; tar --selinux --acls --xattrs -cf - . | (cd /alt_home; tar xf -)"
    ]
  }

  # reboot vm to mount /var
  provisioner "shell" {
    remote_folder = "/home/packer"
    inline = [
      "sudo sed -i 's#/alt_#/#' /etc/fstab",
    ]
  }

  provisioner "breakpoint" {
    disable = false
    note    = "reboot next"
  }

  # reboot vm to mount /var
  provisioner "shell" {
    remote_folder = "/home/packer"
    inline = [
      "sudo reboot"
    ]
    expect_disconnect = true
    pause_after = "60s"
  }

  provisioner "breakpoint" {
    disable = false
    note    = "post reboot"
  }
}
```

cloud-init config
```
#cloud-config

disk_setup:
  /dev/disk/azure/scsi1/lun0:
    table_type: gpt
    layout: 
      - 15
      - 14
      - 28
      - 14
      - 14
      - 14
    overwrite: True

fs_setup:
  - device: /dev/disk/azure/scsi1/lun0
    partition: 1
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 2
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 3
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 4
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 5
    filesystem: ext4
  - device: /dev/disk/azure/scsi1/lun0
    partition: 6
    filesystem: ext4

mounts:
 - [ "/dev/disk/azure/scsi1/lun0-part1", "/alt_home", "auto", "defaults,nofail", "0", "2" ]

package_update: true

packages:
 - vim
 - less
```
