### ISSUE TITLE
cloud-init status --wait hangs forever if bootcmd fails

### ISSUE THREAD

**Issue by pieter-lautus** [canonical/cloud-init#4505]
# Bug report
When a bootcmd fails, `cloud-init status --long` reports status `running` instead of `error`. Likely for this reason, `cloud-init status --wait` will hang indefinitely, instead of exiting with an error code.

## Steps to reproduce the problem
We discovered this bug in the context of an LXD container, but that is likely irrelevant to the issue at hand.

1. Run:
```
lxc launch images:ubuntu/20.04 foo
lxc shell foo
apt install cloud-init
```
2. Create `/etc/cloud/cloud.cfg.d/99_broken.cfg` with the following contents:
```
bootcmd:
- exit 1
```
3. Run `systemctl restart cloud-init`. It will fail, as expected.
4. Run `cloud-init status --long`. You will see something like:
  ```
  status: running
  boot_status_code: enabled-by-generator
  last_update: Thu, 12 Oct 2023 05:57:39 +0000
  detail:
  ('bootcmd', ProcessExecutionError("Unexpected error while running command.\nCommand: ['/bin/sh', '/run/cloud-init/tmp/tmpec2a_i74.sh']\nExit code: 1\nReason: -\nStdout: -\nStderr: -"))
  ```
  The status `running` looks wrong.
5. Run `cloud-init status --wait`. It will run indefinitely, which is wrong.
6. Run `apt install cloud-init=20.1-10-g71af48df-0ubuntu5`
7. Run `systemctl restart cloud-init`. It will fail, as expected.
8. Run `cloud-init status --long --wait`. It will immediately fail, as expected, with the expected output:
```
status: error
time: Thu, 12 Oct 2023 06:00:29 +0000
detail:
('bootcmd', ProcessExecutionError("Unexpected error while running command.\nCommand: ['/bin/sh', '/run/cloud-init/tmp/tmp0n300745.sh']\nExit code: 1\nReason: -\nStdout: -\nStderr: -"))
```

## Environment details
- Cloud-init version: 23.3.1-0ubuntu1~20.04.1
- Operating System Distribution: Ubuntu 20.04 LXD image from https://cloud-images.ubuntu.com/releases
- Cloud provider, platform or installer type: LXD

## cloud-init logs
[cloud-init.tar.gz](https://github.com/canonical/cloud-init/files/12877890/cloud-init.tar.gz)
