### ISSUE TITLE
ENI and Network-Manager renderers create wrong IPv6 routes

### ISSUE THREAD

**Issue by karibou** [canonical/cloud-init#4518]
# Bug report
When defining IPv6 route in the v2 network config yaml, the IPv6 route is wrongly defined. The Network-Manager renderer adds it to the [ipv4] section.

## Steps to reproduce the problem
Using the following network-config : 
```
# cat config.yaml
version: 2
ethernets:
  eth0:
    dhcp4: true
    routes:
      - to: 169.254.42.42/32
        via: 62.210.0.1
      - via: fe80::dc00:ff:fe20:186
        to: ::/0
    addresses:
      - 2001:bc8:1210:232:dc00:ff:fe20:185/64
```
 when creating a Network-Manager configuration using : 
```
cloud-init devel net-convert -p config.yaml -k yaml -d . -D centos -O network-manager
```
The [ipv4] section has : 
```
[ipv4]
method=auto
may-fail=false
route1=169.254.42.42/32,62.210.0.1
route2=::/0,fe80::dc00:ff:fe20:186
```
As seen the IPv6 route gets added to the IPv4 section

## Environment details
- Cloud-init version: 23.3.1-0ubuntu1~22.04.1
- Operating System Distribution: Ubuntu Jammy
- Cloud provider, platform or installer type: Scaleway

## cloud-init logs
No logs are necessary, the behavior can be reproduced at will using the cloud-init command
