### ISSUE TITLE
`merge_how` property missed in yaml-schema

### ISSUE THREAD

**Issue by psydvl** [canonical/cloud-init#4647]
# Bug report
PR https://github.com/canonical/cloud-init/pull/4562 added top level properties, but missed at least `merge_how`

## Steps to reproduce the problem
- Run VSCode with YAML plugin
- Open valid cloud-init file like
  ```yaml
  #cloud-config
  merge_how:
    - name: list
      settings: [append]
    - name: dict
      settings: [no_replace, recurse_list]
  ```

Documentation about property: https://cloudinit.readthedocs.io/en/latest/reference/merging.html#example-cloud-config
