### ISSUE TITLE
[docs]: why do you hate people with eyeballs?

### ISSUE THREAD

**Issue by lsh-0** [canonical/cloud-init#4759]
# ~Documentation~ Explanation request

The current colours are blinding and difficult to read:

![Screenshot at 2024-01-10 14-52-04](https://github.com/canonical/cloud-init/assets/2142748/7a3c1991-c98a-4231-84e6-5361cf314411)

Reader-mode helps:

![Screenshot at 2024-01-10 14-56-40](https://github.com/canonical/cloud-init/assets/2142748/5372f060-a5b0-4fbf-a84b-b1be15d3544d)

But navigation is lost. 

Dark mode has the inverse problem, where fonts are thin and small and get lost in the darkness so you end up peering and squinting at the page:

![Screenshot at 2024-01-10 15-00-52](https://github.com/canonical/cloud-init/assets/2142748/546eec49-b531-4600-9e0d-84f87a483e23)

A previous version of the docs was much, *much*, easier on the eyes:

![Screenshot at 2024-01-10 14-53-50](https://github.com/canonical/cloud-init/assets/2142748/7568044d-2ed8-42b7-814b-a3c8534021dc)

And with a little tweaking, the current site is now more friendly to regular people sporting two eyeballs:

![Screenshot at 2024-01-10 15-05-33](https://github.com/canonical/cloud-init/assets/2142748/28351557-aacf-4737-9bd6-eb38af7e77ce)

**edit**: css overrides:

```css
body {
  background-color: #eee;
  font-family: "bitstream vera sans";
}

.main {
    font-size: 1.2em;
}

.toc-drawer {
  background-color: #eee;
  display: none;
}

.sidebar-drawer {
  background-color: #eee;
}
```

---
*Reported from: https://canonical-cloud-init.readthedocs-hosted.com/en/latest/reference/network-config-format-v2.html*
