### ISSUE TITLE
networkd renderer does not respect accept-ra

### ISSUE THREAD

**Issue by philsphicas** [canonical/cloud-init#4927]
# Bug report

The networkd renderer only includes `IPv6AcceptRA` in the generated files if DHCP is enabled. It should be possible to toggle this setting whenever `accept-ra` is set, for example, to reject RAs when static IPv4 addressing is used.

## Steps to reproduce the problem

This network-config:

```yaml
network:
    config:
    -   accept-ra: false
        mac_address: 00:11:22:33:44:55
        name: eth0
        subnets:
        -   address: 10.0.0.10/24
            type: static
        type: physical
    version: 1
```

Should render as:

```ini
[Address]
Address=10.0.0.10/24

[Match]
MACAddress=00:11:22:33:44:55
Name=eth0

[Network]
DHCP=no
IPv6AcceptRA=False
```
