### ISSUE TITLE
default user "ubuntu" with locked password

### ISSUE THREAD

**Issue by erSitzt** [canonical/cloud-init#4946]
similar to this issue #4072

I'm building ubuntu templates with packer using `ubuntu-22.04.3-live-server-amd64.iso`
i create/setup two users:
- Default user (ubuntu)
- ansible

Password hash works , as i can log in using the ansible user.
Ubuntu user does not work. This was working somewhere around a year ago, because older 20.04 and i think 22.04 templates/vms still work.

as you can see in `/etc/shadow` the ubuntu user is prefixed with an exclamation mark
```
ansible:$6$rounds=4096$N2CzjWelQcBt48$nNyIeaoGQTUEvUj2mba8d7t1oO2g1pmuAHMwdqwOEB61dwLgN8W.FPsu79R2FeMuBjc2PeCwHlzEx4xso3Fe0:19776:0:99999:7:::
ubuntu:!$6$rounds=4096$N2CzjWelQcBt48$nNyIeaoGQTUEvUj2mba8d7t1oO2g1pmuAHMwdqwOEB61dwLgN8W.FPsu79R2FeMuBjc2PeCwHlzEx4xso3Fe0:19776:0:99999:7:::
```

```
#cloud-config
autoinstall:
    version: 1
#    network:
#        network:
#            version: 2
#            ethernets:
#                ens192:
#                    dhcp4: true
#                    dhcp-identifier: mac
    early-commands:
        # Stop ssh for packer
        - sudo systemctl stop ssh
    locale: de_DE
    keyboard:
        layout: de
    ssh:
        install-server: yes
        allow-pw: yes
    storage:
        layout:
            name: direct
    apt:
        primary:
            - arches: [i386, amd64]
              uri: "http://de.archive.ubuntu.com/ubuntu/"
    packages:
        - open-vm-tools
    user-data:
        package_update: false
        package_upgrade: false
        package_reboot_if_required: false
        disable_root: false
        timezone: Europe/Berlin
        users:
        - default
        - name: ansible
          passwd: $6$rounds=4096$N2CzjWelQcBt48$nNyIeaoGQTUEvUj2mba8d7t1oO2g1pmuAHMwdqwOEB61dwLgN8W.FPsu79R2FeMuBjc2PeCwHlzEx4xso3Fe0
          shell: /bin/bash
          lock-passwd: false
          sudo: ALL=(ALL) NOPASSWD:ALL
          groups: users, admin
        chpasswd:
          expire: false
          list:
            - ubuntu:$6$rounds=4096$N2CzjWelQcBt48$nNyIeaoGQTUEvUj2mba8d7t1oO2g1pmuAHMwdqwOEB61dwLgN8W.FPsu79R2FeMuBjc2PeCwHlzEx4xso3Fe0
    late-commands:
        - sed -i -e 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/g' /target/etc/ssh/sshd_config
        - sed -i -e 's/^#\?PermitRootLogin.*/PermitRootLogin yes/g' /target/etc/ssh/sshd_config
#        - sed -i 's/^#*\(send dhcp-client-identifier\).*$/\1 = hardware;/' /etc/dhcp/dhclient.conf

```

**Comment by TheRealFalcon** [comment]
@erSitzt , I am unable to reproduce this issue, but it's important to note that the config you provided is an autoinstall config for the Ubuntu installer, which is called subiquity. This issue tracker is for cloud-init. That said, I do see that you have cloud-init user data embedded in your config, and cloud-init is the one to create your users.

Using this as my userdata:
```
#cloud-config
package_update: false
package_upgrade: false
package_reboot_if_required: false
disable_root: false
timezone: Europe/Berlin
users:
- default
- name: ansible
  passwd: $6$rounds=4096$N2CzjWelQcBt48$nNyIeaoGQTUEvUj2mba8d7t1oO2g1pmuAHMwdqwOEB61dwLgN8W.FPsu79R2FeMuBjc2PeCwHlzEx4xso3Fe0
  shell: /bin/bash
  lock-passwd: false
  sudo: ALL=(ALL) NOPASSWD:ALL
  groups: users, admin
chpasswd:
  expire: false
  list:
    - ubuntu:$6$rounds=4096$N2CzjWelQcBt48$nNyIeaoGQTUEvUj2mba8d7t1oO2g1pmuAHMwdqwOEB61dwLgN8W.FPsu79R2FeMuBjc2PeCwHlzEx4xso3Fe0
```

I created a jammy container:
```
$ lxc launch ubuntu:jammy test -c user.user-data="$(cat cloud-config.yaml)"`
```

Then checked the result:
```
$ lxc shell test                                                               
root@test:~# cloud-init status --wait

status: done
root@test:~# cat /etc/shadow
root:*:19776:0:99999:7:::
daemon:*:19776:0:99999:7:::
bin:*:19776:0:99999:7:::
sys:*:19776:0:99999:7:::
sync:*:19776:0:99999:7:::
games:*:19776:0:99999:7:::
man:*:19776:0:99999:7:::
lp:*:19776:0:99999:7:::
mail:*:19776:0:99999:7:::
news:*:19776:0:99999:7:::
uucp:*:19776:0:99999:7:::
proxy:*:19776:0:99999:7:::
www-data:*:19776:0:99999:7:::
backup:*:19776:0:99999:7:::
list:*:19776:0:99999:7:::
irc:*:19776:0:99999:7:::
gnats:*:19776:0:99999:7:::
nobody:*:19776:0:99999:7:::
systemd-network:*:19776:0:99999:7:::
systemd-resolve:*:19776:0:99999:7:::
messagebus:*:19776:0:99999:7:::
systemd-timesync:*:19776:0:99999:7:::
syslog:*:19776:0:99999:7:::
_apt:*:19776:0:99999:7:::
tss:*:19776:0:99999:7:::
uuidd:*:19776:0:99999:7:::
tcpdump:*:19776:0:99999:7:::
sshd:*:19776:0:99999:7:::
pollinate:*:19776:0:99999:7:::
landscape:*:19776:0:99999:7:::
fwupd-refresh:*:19776:0:99999:7:::
ansible:$6$rounds=4096$N2CzjWelQcBt48$nNyIeaoGQTUEvUj2mba8d7t1oO2g1pmuAHMwdqwOEB61dwLgN8W.FPsu79R2FeMuBjc2PeCwHlzEx4xso3Fe0:19776:0:99999:7:::
ubuntu:$6$rounds=4096$N2CzjWelQcBt48$nNyIeaoGQTUEvUj2mba8d7t1oO2g1pmuAHMwdqwOEB61dwLgN8W.FPsu79R2FeMuBjc2PeCwHlzEx4xso3Fe0:19776:0:99999:7:::
lxd:!:19776::::::
root@test:~# 
```

The `ubuntu` user does not have the `!`.

Can you reproduce it using cloud-init alone? If so, can you provide the cloud-init version you're using and any other relevant environment details?
