### ISSUE TITLE
Ubuntu : VMware extra_config guestinfo.userdata not used after switching from 22.04.1 to 22.04.2 or later

### ISSUE THREAD

**Issue by erSitzt** [canonical/cloud-init#4977]
# Bug report

I'm using Packer to create a VMware template, which is later deployed using terraform.
This is/was working fine until i updated the base-iso for the packer template to 22.04.2 or higher.
During the packer template build i run `apt-get dist-upgrade` and using either base iso i end up with an up to date ubuntu template.
Terraform uses `extra_config` with `guestinfo.userdata` and `guestinfo.metadata`  to make minimal changes like network config, ssh pubkey for a user and installing some packages.

extra_config from terraform config:
```
  extra_config = {
    "guestinfo.metadata" = base64encode(templatefile("${path.module}/templates/metadata.yml.tpl", {
      node_ip       = "${var.vm_server_network}${count.index +  var.vm_server_startip}/${var.vm_server_netmask}",
      node_gateway  = var.vm_server_gateway,
      node_dns      = var.vm_dns,
      node_hostname = "${var.vm_server_prefix}${count.index + 1}"
    }))

    "guestinfo.metadata.encoding" = "base64"

    "guestinfo.userdata" = base64encode(templatefile("${path.module}/templates/userdata.yml.tpl", {
      vm_ssh_user = var.vm_ssh_user,
      vm_ssh_key = var.vm_ssh_key
    }))
    "guestinfo.userdata.encoding" = "base64"
  }
```

metadata:
```
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false
      addresses:
        - ${node_ip}
      gateway4: ${node_gateway}
      nameservers:
        addresses:
          - ${node_dns}
local-hostname: ${node_hostname}
instance-id: ${node_hostname}
```
userdata:
```
#cloud-config
users:
  - name: ${vm_ssh_user}
    ssh-authorized-keys:
      - ${vm_ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
runcmd:
  - sudo apt-get remove -y docker docker-engine docker.io containerd runc
  - sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release open-iscsi nfs-common
```
nothing special..

as soon as i switch to the newer ubuntu iso, both are no longer used to configure the VM.
Packer and Terraform scripts remain unchanged.

I can see the userdata/metadata in the VMs config and i can query it with 
```
vmware-rpctool "info-get guestinfo.metadata" | base64 -d
vmware-rpctool "info-get guestinfo.userdata" | base64 -d
```

## Steps to reproduce the problem
Not sure yet.. i'll try to set up a barebones packer/terraform or try it with the examples projects to see if i can reproduce.

## Environment details
- Cloud-init version:
`/usr/bin/cloud-init 23.4.3-0ubuntu0~22.04.1` in both instances
- Operating System Distribution:
Ubuntu 22.04.1 working ( base iso version.. updated to 22.04.4 during template build )
Uubntu 22.04.2+ not working ( base iso version.. all updated to 22.04.4 in the template build process )

- Cloud provider, platform or installer type:

## cloud-init logs
Will attach after i have rerun with both base isos.
