### ISSUE TITLE
Yum repo module should not only accept baseurl as required. Should accept metalink or baseurl as required

### ISSUE THREAD

**Issue by bengaywins** [canonical/cloud-init#5359]
# Bug report
In creation of a Yum repo with the module, it requires the `baseurl` parameter. With some repos (like epel), it is desired to use a metalink. Which is interpreted by dnf/yum differently than baseurl. As such, the evaluation of a missing baseurl should only fail if there is no metalink specified.

## Steps to reproduce the problem
1. use the following code to create a yum repo:
```yaml
yum_repos:
  epel-release:
    metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir
    enabled: true
    failovermethod: priority
    gpgcheck: true
    gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    name: epel-release
```

## Environment details
- Cloud-init version: 23.4-7.el9_4.0.1
- Operating System Distribution: rocky linux
- Cloud provider, platform or installer type: aws

## cloud-init logs
```
2024-06-03 19:34:57,168 - cc_yum_add_repo.py[WARNING]: Repository epel-release does not contain a baseurl configuration 'required' entry
2024-06-03 19:34:57,168 - cc_yum_add_repo.py[WARNING]: Repository epel-release is missing 1 required fields, skipping!
```
