### ISSUE TITLE
[enhancement]: Implement ipv6-address-token / ip token set ::123

### ISSUE THREAD

**Issue by Sprinterfreak** [canonical/cloud-init#5377]
# Enhancement

In SLAAC deployments, interface tokens are used to override the host-bits with a predictable and short value.
Would be nice to be able to set this token via cloud-init too, to make ipv6-addresses somewhat predictable/readable in dynamic prefix environments.

The resulting configuration would be in netplan:
```yaml
network:
  ethernets:
    eth0:
      ipv6-address-token: ::123
```

/etc/network/interfaces
```
iface eth0 inet6 auto
  up ip token set ::123 dev $IFACE
```

**Comment by aciba90** [comment]
Hello @Sprinterfreak. This is already supported in systems with netplan by [netplan-passthrough](https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v2.html#netplan-passthrough). Is your request more broad support for other network stacks?

**Comment by Sprinterfreak** [comment]
Hi, my goal is to have a stable solution to promote to specifically proxmox community/devs to adopt.
Since there is a variety of distros and therefore different network manager's out there, so it would be preferable to have it in the network-config file and scripts taking care of rendering it out into different network managers config formats:

```yaml
version: 1
config:
    - type: physical
      name: eth0
      mac_address: 'a6:af:ba:66:f6:50'
      subnets:
      - type: static
        address: '10.20.30.7'
        netmask: '255.255.255.0'
        gateway: '10.20.30.1'
      - type: ipv6_slaac
        token: ::123                        <-------
    - type: nameserver
      address:
      - '10.20.30.1'
      - 'fd12:34::1'
      search:
      - 'domain.tld'
```
