### ISSUE TITLE
[enhancement]: Schema validator run from `main_init` can produce confusing error messages

### ISSUE THREAD

**Issue by ani-sinha** [canonical/cloud-init#5399]
# Enhancement
We have a customer who has raised some serious concerns over confusing warning messages produced by the schema validator that is run from `main_init` in stage 7 in the following hunk of code :

```
  # Validate user-data adheres to schema definition                                                                                                                                             
    cloud_cfg_path = init.paths.get_ipath_cur("cloud_config")
    if os.path.exists(cloud_cfg_path) and os.stat(cloud_cfg_path).st_size != 0:
        validate_cloudconfig_schema(
            config=yaml.safe_load(util.load_text_file(cloud_cfg_path)),
            strict=False,
            log_details=False,
            log_deprecations=True,
        )
    else:
        LOG.debug("Skipping user-data validation. No user-data found.")
```
For example, with the following configuration:

```
#cloud-config

users:
  - name: osadmin
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh-authorized-keys:
      - ssh-rsa "AAAAB3NzaC1yc2EAAAADAQABAAABAQCc/K1T62elOkJKc94sWovn06RE7D274Fxx5n+eT/oClAwk7632awMtWjO+lIRpzOlEcYCR6wexlmL9mZNEFJoROMMRyCxRilNAiDKOq0X5j1HXY2ky9KjtLxo2b8yXFRBcYKK4W8aHU94NkNek81jdi9lC+L6jUrZ25d7xylqnEbd4TgrBphiowdh5B3RY+j6ePthLWWhHopRcVDgq91yYacelCCIfSDaGBya9iXPZSwoKtPin4n5PdSGmSOA3fIkvV5JjLS1QbuY5tzhXKuH9MdAqrvutF1bprs/GDf0IY8DO7DDoo8rXjhhgGtCdg1i5UitZIAM3hn/Vk5F//5eJ JOOS8312@EB-OR6120158"
 ```

raises the schema errors on the lines:
(1) `sudo: ["ALL=(ALL) NOPASSWD:ALL"]` and 
(2) `ssh-authorized-keys:`

and this will generate a warning message while starting cloud-init :

```
[   13.764433] cloud-init[973]: 2024-05-13 08:36:30,490 - schema.py[WARNING]: Invalid cloud-config provided: Please run 'sudo cloud-init schema --system' to see the schema errors.
```

The schema validator complains because the schema definition says
```
      "sudo": {
          "oneOf": [
            {
              "type": [
                "string",
                "null"
              ],
              "description": "Sudo rule to use or false. Absence of a sudo value or ``null`` will result in no sudo rules added for this user."
            },
            {
              "type": "boolean",
              "changed": true,
              "changed_version": "22.2",
              "changed_description": "The value ``false`` is deprecated for this key, use ``null`` instead."
            }
          ]
```

Therefore, the `sudo` attribute is one of string (or `null`) or a boolean (deprecated) or `null` value. 
As for `ssh-authorized-keys`, it seems this syntax is deprecated as per the schema definition:

```
       "ssh-authorized-keys": {
          "allOf": [
            {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1
            },
            {
              "deprecated": true,
              "deprecated_version": "18.3",
              "deprecated_description": "Use ``ssh_authorized_keys`` instead."
            }
          ]
        },
```
Fair enough to complain from the schema validator's perspective. However, in reality, the config provided by the customer also works just fine.
This is because, in `write_sudo_rules()` under `distros/__init__`, it specifically checks for a `list` type and extracts the strings from it:
```
     if isinstance(rules, (list, tuple)):
            for rule in rules:
                lines.append("%s %s" % (user, rule))
        elif isinstance(rules, str):
            lines.append("%s %s" % (user, rules))
        else:
            msg = "Can not create sudoers rule addition with type %r"
            raise TypeError(msg % (type_utils.obj_name(rules)))
```
For `ssh-authorized-keys`, it is still ok to use the deprecated syntax and it does not break functionality.

Therefore, in reality the config works. Yet when the users find the warning message, it produces an impression that the config is broken and would require to be adjusted. It may also break automation tools that are looking for specific error signatures.

I believe this situation can be improved. While it is important to warn users of config syntaxes that violate the schema definition or use of deprecated syntaxes, I think we should try to avoid such confusion and impression that something is functionally broken. This ticket is raised to address this concern and figure out a better mechanism to inform users of bad config syntaxes without causing confusion.
