### ISSUE TITLE
[enhancement]: schema validator complains about non-canonical names but they do indeed work

### ISSUE THREAD

**Issue by ani-sinha** [canonical/cloud-init#5454]
# Enhancement

Please https://github.com/canonical/cloud-init/pull/5418#issuecomment-2190489650 as a part of the PR https://github.com/canonical/cloud-init/pull/5418 . 

The schema validator complains that `ssh-authorized-keys` (and likely other parameters with a `-` instead of `_` ) are invalid. Yet, the `ug_util.py` has this logic

```
    # Ensure user options are in the right python friendly format                                                                                                                                 
    if users:
        c_users = {}
        for uname, uconfig in users.items():
            c_uconfig = {}
            for k, v in uconfig.items():
                k = k.replace("-", "_").strip()
                if k:
                    c_uconfig[k] = v
            c_users[uname] = c_uconfig
        users = c_users

```
Thus `-` work. So what to do about this? The schema validator can ignore differences between names with- and names with _ with a warning to place it to canonical form.

**Comment by ani-sinha** [comment]
This is the config used:

```
bootcmd:
- echo "hello bootcmd" >> /etc/motd
runcmd:
- echo "hello runcmd" >> /etc/motd
users:
- default
-   lock_passwd: false		# E1,E2,E3
    name: huzhaotest
    ssh-authorized-keys:
    - ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfBNjpFH7KTVlbMY67tAhdvWPiSGi2KY5OFRcBCONXioef1MD7nathW3KwgF8GQMSukdcsAK6Ml5KpqporYSaXzOnIHPspfd/wt0JEj1WWe9ZWrC75TVS+X+tcLhZGsKviF/9tZfei6fcejCN8VRQscZCKy4c15cwsFvXWlK0hemiDilMWWP6eJQVLLtzdtw/xxNha2EKth/ETUTZz3DXBrrSmiZbchqEHZEK0F2PgEmn9qTtezBM/F0+uQh3P3SaOG2gKho3dbmGQSYasZLSTT/vsgK8WJp/uB+PPs8o0SKGcAPVMfGnec0ieNBp2SQSFrJiz8PDl7F2flDlx1UMPmUlKn3xyO+jF7k9m97lKvN9r+eiU5qKyzLAfWQoYkArytCJ5A/75Sc61FtnXoRy1US7cpDyLvcUFTdy1uRxhkH3FjoEpT6h4yTFkCkZzM7cudMKb8JcFL5TbLSmaHYJDaeVHIAm2d9DS+bT//8MDFIycVHlgJOYp9c8cQ3i1pN8=
        huzhao@dhcp-93-177.nay.redhat.com"
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
```
This is the error:

```
# Errors: -------------
# E1: Additional properties are not allowed ('ssh-authorized-keys' was unexpected)
# E2: {'lock_passwd': False, 'name': 'huzhaotest', 'ssh-authorized-keys': ['ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfBNjpFH7KTVlbMY67tAhdvWPiSGi2KY5OFRcBCONXioef1MD7nathW3KwgF8GQMSukdcsAK6Ml5KpqporYSaXzOnIHPspfd/wt0JEj1WWe9ZWrC75TVS+X+tcLhZGsKviF/9tZfei6fcejCN8VRQscZCKy4c15cwsFvXWlK0hemiDilMWWP6eJQVLLtzdtw/xxNha2EKth/ETUTZz3DXBrrSmiZbchqEHZEK0F2PgEmn9qTtezBM/F0+uQh3P3SaOG2gKho3dbmGQSYasZLSTT/vsgK8WJp/uB+PPs8o0SKGcAPVMfGnec0ieNBp2SQSFrJiz8PDl7F2flDlx1UMPmUlKn3xyO+jF7k9m97lKvN9r+eiU5qKyzLAfWQoYkArytCJ5A/75Sc61FtnXoRy1US7cpDyLvcUFTdy1uRxhkH3FjoEpT6h4yTFkCkZzM7cudMKb8JcFL5TbLSmaHYJDaeVHIAm2d9DS+bT//8MDFIycVHlgJOYp9c8cQ3i1pN8= huzhao@dhcp-93-177.nay.redhat.com"'], 'sudo': ['ALL=(ALL) NOPASSWD:ALL']} is not of type 'array'
# E3: {'lock_passwd': False, 'name': 'huzhaotest', 'ssh-authorized-keys': ['ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfBNjpFH7KTVlbMY67tAhdvWPiSGi2KY5OFRcBCONXioef1MD7nathW3KwgF8GQMSukdcsAK6Ml5KpqporYSaXzOnIHPspfd/wt0JEj1WWe9ZWrC75TVS+X+tcLhZGsKviF/9tZfei6fcejCN8VRQscZCKy4c15cwsFvXWlK0hemiDilMWWP6eJQVLLtzdtw/xxNha2EKth/ETUTZz3DXBrrSmiZbchqEHZEK0F2PgEmn9qTtezBM/F0+uQh3P3SaOG2gKho3dbmGQSYasZLSTT/vsgK8WJp/uB+PPs8o0SKGcAPVMfGnec0ieNBp2SQSFrJiz8PDl7F2flDlx1UMPmUlKn3xyO+jF7k9m97lKvN9r+eiU5qKyzLAfWQoYkArytCJ5A/75Sc61FtnXoRy1US7cpDyLvcUFTdy1uRxhkH3FjoEpT6h4yTFkCkZzM7cudMKb8JcFL5TbLSmaHYJDaeVHIAm2d9DS+bT//8MDFIycVHlgJOYp9c8cQ3i1pN8= huzhao@dhcp-93-177.nay.redhat.com"'], 'sudo': ['ALL=(ALL) NOPASSWD:ALL']} is not of type 'string'
```

Once I change the `ssh-authorized-keys` to `ssh_authorized_keys`, schema validator no longer complains.

**Comment by ani-sinha** [comment]
@holmanb please feel free to take a look.

**Comment by blackboxsw** [comment]
Thanks @ani-sinha for the communication on this. We'll try pulling this into 24.2 release

**Comment by blackboxsw** [comment]
Related PR up for review https://github.com/canonical/cloud-init/pull/5456

**Comment by holmanb** [comment]
> This is the config used:
> 
> ```
> bootcmd:
> - echo "hello bootcmd" >> /etc/motd
> runcmd:
> - echo "hello runcmd" >> /etc/motd
> users:
> - default
> -   lock_passwd: false		# E1,E2,E3
>     name: huzhaotest
>     ssh-authorized-keys:
>     - ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfBNjpFH7KTVlbMY67tAhdvWPiSGi2KY5OFRcBCONXioef1MD7nathW3KwgF8GQMSukdcsAK6Ml5KpqporYSaXzOnIHPspfd/wt0JEj1WWe9ZWrC75TVS+X+tcLhZGsKviF/9tZfei6fcejCN8VRQscZCKy4c15cwsFvXWlK0hemiDilMWWP6eJQVLLtzdtw/xxNha2EKth/ETUTZz3DXBrrSmiZbchqEHZEK0F2PgEmn9qTtezBM/F0+uQh3P3SaOG2gKho3dbmGQSYasZLSTT/vsgK8WJp/uB+PPs8o0SKGcAPVMfGnec0ieNBp2SQSFrJiz8PDl7F2flDlx1UMPmUlKn3xyO+jF7k9m97lKvN9r+eiU5qKyzLAfWQoYkArytCJ5A/75Sc61FtnXoRy1US7cpDyLvcUFTdy1uRxhkH3FjoEpT6h4yTFkCkZzM7cudMKb8JcFL5TbLSmaHYJDaeVHIAm2d9DS+bT//8MDFIycVHlgJOYp9c8cQ3i1pN8=
>         huzhao@dhcp-93-177.nay.redhat.com"
>     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
> ```
> 
> This is the error:
> 
> ```
> # Errors: -------------
> # E1: Additional properties are not allowed ('ssh-authorized-keys' was unexpected)
> # E2: {'lock_passwd': False, 'name': 'huzhaotest', 'ssh-authorized-keys': ['ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfBNjpFH7KTVlbMY67tAhdvWPiSGi2KY5OFRcBCONXioef1MD7nathW3KwgF8GQMSukdcsAK6Ml5KpqporYSaXzOnIHPspfd/wt0JEj1WWe9ZWrC75TVS+X+tcLhZGsKviF/9tZfei6fcejCN8VRQscZCKy4c15cwsFvXWlK0hemiDilMWWP6eJQVLLtzdtw/xxNha2EKth/ETUTZz3DXBrrSmiZbchqEHZEK0F2PgEmn9qTtezBM/F0+uQh3P3SaOG2gKho3dbmGQSYasZLSTT/vsgK8WJp/uB+PPs8o0SKGcAPVMfGnec0ieNBp2SQSFrJiz8PDl7F2flDlx1UMPmUlKn3xyO+jF7k9m97lKvN9r+eiU5qKyzLAfWQoYkArytCJ5A/75Sc61FtnXoRy1US7cpDyLvcUFTdy1uRxhkH3FjoEpT6h4yTFkCkZzM7cudMKb8JcFL5TbLSmaHYJDaeVHIAm2d9DS+bT//8MDFIycVHlgJOYp9c8cQ3i1pN8= huzhao@dhcp-93-177.nay.redhat.com"'], 'sudo': ['ALL=(ALL) NOPASSWD:ALL']} is not of type 'array'
> # E3: {'lock_passwd': False, 'name': 'huzhaotest', 'ssh-authorized-keys': ['ssh-rsa "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfBNjpFH7KTVlbMY67tAhdvWPiSGi2KY5OFRcBCONXioef1MD7nathW3KwgF8GQMSukdcsAK6Ml5KpqporYSaXzOnIHPspfd/wt0JEj1WWe9ZWrC75TVS+X+tcLhZGsKviF/9tZfei6fcejCN8VRQscZCKy4c15cwsFvXWlK0hemiDilMWWP6eJQVLLtzdtw/xxNha2EKth/ETUTZz3DXBrrSmiZbchqEHZEK0F2PgEmn9qTtezBM/F0+uQh3P3SaOG2gKho3dbmGQSYasZLSTT/vsgK8WJp/uB+PPs8o0SKGcAPVMfGnec0ieNBp2SQSFrJiz8PDl7F2flDlx1UMPmUlKn3xyO+jF7k9m97lKvN9r+eiU5qKyzLAfWQoYkArytCJ5A/75Sc61FtnXoRy1US7cpDyLvcUFTdy1uRxhkH3FjoEpT6h4yTFkCkZzM7cudMKb8JcFL5TbLSmaHYJDaeVHIAm2d9DS+bT//8MDFIycVHlgJOYp9c8cQ3i1pN8= huzhao@dhcp-93-177.nay.redhat.com"'], 'sudo': ['ALL=(ALL) NOPASSWD:ALL']} is not of type 'string'
> ```
> 
> Once I change the `ssh-authorized-keys` to `ssh_authorized_keys`, schema validator no longer complains.

I couldn't reproduce the reported issue from main. Are you sure this wasn't fixed already in [this PR](?)https://github.com/canonical/cloud-init/commit/5205b4dd74eb2168ebbeba56579b6f116a272937

Your example configuration isn't valid cloud-config, but I came up with something that is based on what you shared:
```yaml
#cloud-config
bootcmd:
  - echo "hello bootcmd" >> /etc/motd
runcmd:
  - echo "hello runcmd" >> /etc/motd
users:
  - default
  - name: example
    lock_passwd: false
    name: huzhaotest
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfBNjpFH7KTVlbMY67tAhdvWPiSGi2KY5OFRcBCONXioef1MD7nathW3KwgF8GQMSukdcsAK6Ml5KpqporYSaXzOnIHPspfd/wt0JEj1WWe9ZWrC75TVS+X+tcLhZGsKviF/9tZfei6fcejCN8VRQscZCKy4c15cwsFvXWlK0hemiDilMWWP6eJQVLLtzdtw/xxNha2EKth/ETUTZz3DXBrrSmiZbchqEHZEK0F2PgEmn9qTtezBM/F0+uQh3P3SaOG2gKho3dbmGQSYasZLSTT/vsgK8WJp/uB+PPs8o0SKGcAPVMfGnec0ieNBp2SQSFrJiz8PDl7F2flDlx1UMPmUlKn3xyO+jF7k9m97lKvN9r+eiU5qKyzLAfWQoYkArytCJ5A/75Sc61FtnXoRy1US7cpDyLvcUFTdy1uRxhkH3FjoEpT6h4yTFkCkZzM7cudMKb8JcFL5TbLSmaHYJDaeVHIAm2d9DS+bT//8MDFIycVHlgJOYp9c8cQ3i1pN8= huzhao@dhcp-93-177.nay.redhat.com"
```
