### ISSUE TITLE
Apt configure doesn't set up custom keys for primary/security on Noble

### ISSUE THREAD

**Issue by KellenRenshaw** [canonical/cloud-init#5473]
# Bug report
When using the "apt:" module to configure a local mirror for the "primary" and "security" keys, if the mirror is signed by a local key, the rendered ubuntu.sources file still has "Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg" instead of pointing to the file presumably generated from the "key" key.

## Steps to reproduce the problem
Attempt to use a local mirror signed with a non-standard key, like so:
```yaml
config:
  user.user-data: |
    #cloud-config
    apt:
      primary:
        - arches: [default]
          uri: http://apt.example.net/ubuntu/
          key: |
            -----BEGIN PGP PUBLIC KEY BLOCK-----
           <snip>
```

Launch a Noble container with "apt update" in the runcmd, it will fail on validating the GPG signatures with:
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY <id>

## Environment details
- Cloud-init version: 24.1.3-0ubuntu3.3
- Operating System Distribution: Ubuntu 24.04
- Cloud provider, platform or installer type: LXD

**Comment by MiRiskyy** [comment]
```yaml
apt:
  primary:
    - arches: [default]
      uri: http://apt.example.net/ubuntu/
      keyid: ABCDEF1234 # Specify key ID instead of inline key
      keyserver: http://my.keyserver.example/
```

The issue seems to be that specifying the inline PGP key is not properly configuring the APT sources to use that key. Instead, specify the key

**Comment by stew3254** [comment]
It also doesn't work with sources

```yaml
#cloud-config
apt:
  preserve_sources_list: false
  sources:
    ubuntu.sources:
      append: false
      filename: ubuntu.sources
      source: <uri>
      key: |
        <key>
```

**Comment by zypA13510** [comment]
Not sure if related, but I just resolved an issue with inline PGP key on Noble.

In my case, the output log says
> Decode error, failed to add key: [key]

The original config that failed with this error:
```yaml
apt:
  sources:
    docker.list:
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
        ...
        -----END PGP PUBLIC KEY BLOCK-----
```

After changing it to the one below the issue is resolved. It might have to do with the extra line after "begin block".
```yaml
apt:
  sources:
    docker.list:
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Comment: 9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
        
        mQINBFit2ioBEADhWpZ8/wvZ6hUTiXOwQHXMAlaFHcPH9hAtr4F1y2+OYdbtMuth
        ...
        -----END PGP PUBLIC KEY BLOCK-----
```
