### ISSUE TITLE
Can't configure mutliple ethernet adapters using cloud-init

### ISSUE THREAD

**Issue by TobiPeterG** [canonical/cloud-init#5517]
# Bug report
Hey there,

we deploy VMs in different networks that each need their own configuration. I want to provide them using cloud-init. However, only one network gets configured, the other one is always ignored.

ip link
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 02:83:8d:fe:25:5e brd ff:ff:ff:ff:ff:ff
    altname enp11s0
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 02:f8:75:57:a6:ff brd ff:ff:ff:ff:ff:ff
    altname enp19s0
    altname ens224
```

This is the cloud-init file (I censored sensitive content):
```
Content-Type: multipart/mixed; boundary="MIMEBOUNDARY"
MIME-Version: 1.0

--MIMEBOUNDARY
Content-Disposition: attachment; filename="cloud-config.yaml"
Content-Transfer-Encoding: 7bit
Content-Type: text/cloud-config
Mime-Version: 1.0

#cloud-config

package_update: true
package_upgrade: true
packages:
  - libxml2-dev
  - libpam-cracklib
  - libpam-krb5
  - nfs-common
  - open-vm-tools
  - htop
  - git
  - python3
  - python3-pip
  - screen
  - tmux
  - curl
  - apt-transport-https
  - ca-certificates
  - wget
  - uidmap
  - iftop
  - cpulimit
  - sysbench
  - nano
  - software-properties-common
  - xmlstarlet

write_files:
  - path: /root/.ssh/ca_user.pub
    permissions: '0644'
    content: |
      CONTENT
  - path: /root/.ssh/authorized_keys
    permissions: '0644'
    content: |
      CONTENT
  - path: /etc/docker/daemon.json
    permissions: '0644'
    content: |
      CONTENT
  - path: /etc/modprobe.d/blacklist-floppy.conf
    permissions: '0644'
    content: |
      blacklist floppy


runcmd:
  - SOme commands
  - shutdown -r now

--MIMEBOUNDARY
Content-Disposition: attachment; filename="cloud-config-network.yaml"
Content-Transfer-Encoding: 7bit
Content-Type: text/cloud-config
Mime-Version: 1.0

#cloud-config
network:
  version: 2
  ethernets:
    eth0:
      match:
        macaddress: 02:83:8d:fe:25:5e
      dhcp4: true
    eth1:
      match:
        macaddress: 02:f8:75:57:a6:ff
      dhcp4: true
    

--MIMEBOUNDARY--

I also tried to put them into different files and seperate parts with no effect.

```
cat /etc/netplan/50-cloud-init.yaml 
```
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        ens192:
            dhcp4: true
            dhcp6: true
            match:
                macaddress: 02:83:8d:fe:25:5e
            set-name: ens192
    version: 2
```

## Steps to reproduce the problem
Use vsphere and vapps to provide cloud-init file, create vm from ovf template

## Environment details
- Cloud-init version: /usr/bin/cloud-init 24.1.3-0ubuntu3.3
- Operating System Distribution: Ubuntu 24.04
- Cloud provider, platform or installer type: Cloud image, OVF image

## cloud-init logs
cat /var/log/cloud-init.log 
https://pastebin.com/Bb112GcN
