### ISSUE TITLE
cloud-init 24.2-0ubuntu1 : Netplan Renderer is not rendering onlink:true when gateway outside of subnet

### ISSUE THREAD

**Issue by karibou** [canonical/cloud-init#5523]
# Bug report
When a gateway IP address is outside of the NIC's subnet, it is sometimes necessary to render the netplan config with `on-link: true`

The version of `systemd-networkd` on Ubuntu Focal refuses to apply the `ip route` command due to the fact that the address of the gateway is outside of the subnet of the NIC. The `onlink` option is required. This does not happen on Jammy and Noble.

This is a similar issue than the one fixed in https://github.com/canonical/cloud-init/pull/4996
## Steps to reproduce the problem
```
# ip a
2: ens2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether de:00:00:62:c5:e9 brd ff:ff:ff:ff:ff:ff
    inet 212.47.xxx.xxx/32 scope global dynamic ens2
       valid_lft 800sec preferred_lft 800sec
    inet6 2001:xxx:xxx:xxxx:xxxx:xx:xxxx:c5e9/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::dc00:ff:fe62:c5e9/64 scope link 
       valid_lft forever preferred_lft forever
# cat netconfig.yaml
version: 2
ethernets:
    ens2:
        addresses:
        - 2001:xxx:xxx:xxxx:xxxx:xx:xxxx:c5e9/64
        dhcp4: true
        routes:
        -   to: 169.254.42.42/32
            via: 62.210.0.1
        -   to: ::/0
            via: fe80::dc00:ff:fe62:c5ea
# cloud-init devel net-convert -p netconfig.yaml -k yaml -d . -D ubuntu -Onetplan
# cat etc/netplan/50-cloud-init.yaml 
# This file is generated from information provided by the datasource.  Changes
# to it will not persist across an instance reboot.  To disable cloud-init's
# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    ethernets:
        ens2:
            addresses:
            - 2001:bc8:710:238c:dc00:ff:fe62:c5e9/64
            dhcp4: true
            routes:
            -   to: 169.254.42.42/32
                via: 62.210.0.1
            -   to: ::/0
                via: fe80::dc00:ff:fe62:c5ea
    version: 2
```
The on-link: true statement is absent even though 62.210.0.1 is outside of the 212.x.x.x subnet

## Environment details
- Cloud-init version: 24.2
- Operating System Distribution: Ubuntu Focal
- Cloud provider, platform or installer type: Scaleway

## syslog logs
This appears in /var/log/syslog as a result of the application of the crafted netplan
```
Jul 18 10:05:59 focal systemd-networkd[668]: ens2: Could not set route: Nexthop has invalid gateway. Network is unreachable
```

**Comment by aciba90** [comment]
Thanks, @kariboum, for reporting this.

Does adding `on-link: true` to the config solve the issue?

```yaml
version: 2
ethernets:
    ens2:
        addresses:
        - 2001:xxx:xxx:xxxx:xxxx:xx:xxxx:c5e9/64
        dhcp4: true
        routes:
        -   to: 169.254.42.42/32
            via: 62.210.0.1
            on-link: true
        -   to: ::/0
            via: fe80::dc00:ff:fe62:c5ea
```

> This does not happen on Jammy and Noble.

That might indicate that the problem comes from the underlying netplan / systemd-networkd.

> cloud-init 24.2-0ubuntu1

Does the error occur in Focal with cloud-init 24.1? I suspect this was not introduced in 24.2.

Assuming this is an issue in cloud-init or an issue that cloud-init should solve: cloud-init might try to load the network-config-v2 that it receives and, if it success, add the `on-link: true` if required. But note that this might fail, because on systems with netplan, users might pass full netplan config not compatible with v2, as cloud-init [passes it through](https://docs.cloud-init.io/en/latest/reference/network-config-format-v2.html#netplan-passthrough) netplan.
