### ISSUE TITLE
'manual' is not one of ['dhcp4', 'dhcp', 'dhcp6', 'static', 'static6', 'ipv6_dhcpv6-stateful', 'ipv6_dhcpv6-stateless', 'ipv6_slaac']

### ISSUE THREAD

**Issue by jorhett** [canonical/cloud-init#5769]
# Bug report

Cloud-init is failing to parse a network.v1 definition created by curtin:

```
2024-10-02 02:20:45,354 - schema.py[WARNING]: Invalid network-config provided:
config.1.subnets.0.type: 'manual' is not one of ['dhcp4', 'dhcp', 'dhcp6', 'static', 'static6', 'ipv6_dhcpv6-stateful', 'ipv6_dhcpv6-stateless', 'ipv6_slaac']
config.2.subnets.0.type: 'manual' is not one of ['dhcp4', 'dhcp', 'dhcp6', 'static', 'static6', 'ipv6_dhcpv6-stateful', 'ipv6_dhcpv6-stateless', 'ipv6_slaac']
config.3.subnets.0.type: 'manual' is not one of ['dhcp4', 'dhcp', 'dhcp6', 'static', 'static6', 'ipv6_dhcpv6-stateful', 'ipv6_dhcpv6-stateless', 'ipv6_slaac']
```

@TheRealFalcon requested that I separate this issue out from #2880 

## Steps to reproduce the problem

This is being generated by `maas`, so recreation steps are overlong, but the generated config for unconfigured/unused interfaces looks like this:

```
- id: enp129s0f1
    mac_address: 34:80:0d:2c:a4:99
    mtu: 1500
    name: enp129s0f1
    subnets:
    - type: manual
    type: physical
  - id: enp129s0f2
    mac_address: 34:80:0d:2c:a4:9a
    mtu: 1500
    name: enp129s0f2
    subnets:
    - type: manual
    type: physical
  - id: enp129s0f3
    mac_address: 34:80:0d:2c:a4:9b
    mtu: 1500
    name: enp129s0f3
    subnets:
    - type: manual
    type: physical
```

This is causing the entire network configuration to fail, such that it is not applied to the interface which is configured.

As I look at this configuration, it does appear that perhaps this is a mistake by curtin?  Should it perhaps be this?

```
    subnets:
    - type: static
      control: manual
```

If my judgement of this is correct, then it should perhaps be considered a documentation error for the network config v1 format as there's actually no description of the type field here: https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v1.html#subnet-ip

## Environment details

- Cloud-init version: `cloud-init-23.4-7.el9_4.6.alma.1.noarch`
- Operating System Distribution: Alma Linux 9.4
- Cloud provider, platform or installer type: MaaS utilizes curtin which creates a cloudconfig like this:

```
#cloud-config
datasource:
  MAAS:
    metadata_url: http://maas.example.com:5248/MAAS/metadata/
```

## cloud-init logs

[cloud-init.tar.gz](https://github.com/user-attachments/files/17233120/cloud-init.tar.gz)
