### ISSUE TITLE
cloud-init ignores kernel command line argument network-config

### ISSUE THREAD

**Issue by jdewinne** [canonical/cloud-init#5806]
# Bug report

When using cloud-init with a Ubuntu 22.04 root filesystem, and booting it with a kernel command line argument `network-config=...`, the argument is ignored and cloud-init uses the fallback config for the netplan configuration.
The expectation would be that the base 64 decoded value of `network-config` is used.

Note: The file `/run/cloud-init/network-config.json` does not get created, which I would expect to be present according to the [docs](https://cloudinit.readthedocs.io/en/latest/reference/network-config.html).
Also, this problem does not happen with Ubuntu 20.04. When using an Ubuntu 20.04 root filesystem the resulting netplan configuration is the one from the kernel command line argument `network-config`.

## Steps to reproduce the problem

Network Config:
```
NETWORK_CONFIG='version: 2
ethernets:
  eth0:
    match:
      macaddress: "aa:ff:00:00:00:01"
    addresses:
      - 172.16.0.2'
# base64 encode the network config on single line
NETWORK_CONFIG=$(echo "$NETWORK_CONFIG" | base64 -w 0)
KERNEL_BOOT_ARGS="console=ttyS0 reboot=k panic=1 pci=off network-config=${NETWORK_CONFIG}"
```

`/proc/cmdline` from within the guest.
```
root@localhost:~# cat /proc/cmdline
console=ttyS0 reboot=k panic=1 pci=off network-config=dmVyc2lvbjogMgpldGhlcm5ldHM6CiAgZXRoMDoKICAgIG1hdGNoOgogICAgICBtYWNhZGRyZXNzOiAiYWE6ZmY6MDA6MDA6MDA6MDEiCiAgICBhZGRyZXNzZXM6CiAgICAgIC0gMTcyLjE2LjAuMgo= root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5 virtio_mmio.device=4K@0xd0001000:6 virtio_mmio.device=4K@0xd0002000:7
```

## Environment details
- Cloud-init version: `23.1.2-0ubuntu0~22.04.1`, same issue with the latest version `24.3.1`
- Operating System Distribution: Ubuntu 22.04
- Cloud provider, platform or installer type: Installation via firecracker.

## cloud-init logs

[cloud-init.tar.gz](https://github.com/user-attachments/files/17321183/cloud-init.tar.gz)

**Comment by TheRealFalcon** [comment]
@jdewinne , unfortunately, I am unable to reproduce this. Furthermore, within the logs you posted, I see a few references to the kernel cmdline, but they do not contain a network config:
```
$ grep -ri "cmdline"
run/cloud-init/cloud-init-generator.log:kernel command line (container[systemd]: pid 1 cmdline): /sbin/init 
run/cloud-init/cloud-init-generator.log:kernel_cmdline found unset
run/cloud-init/ds-identify.log:KERNEL_CMDLINE=/sbin/init 
```

Are you sure it was set correctly? If so, can you provide the steps you use to reproduce this?

**Comment by xavpaice** [comment]
Thanks for following up.

The dmesg output shows:

```
    0.000000] Command line: console=ttyS0 reboot=k panic=1 pci=off network-config=dmVyc2lvbjogMgpldGhlcm5ldHM6CiAgZXRoMDoKICAgIG1hdGNoOgogICAgICBtYWNhZGRyZXNzOiAiYWE6ZmY6MDA6MDA6MDA6MDEiCiAgICBhZGRyZXNzZXM6CiAgICAgIC0gMTcyLjE2LjAuMgo= root=/dev/vda rw virtio_mmio.device=4K@0xd0000000:5 virtio_mmio.device=4K@0xd0001000:6 virtio_mmio.device=4K@0xd0002000:7
```

If I check that base64 network config I get:
```
echo 'dmVyc2lvbjogMgpldGhlcm5ldHM6CiAgZXRoMDoKICAgIG1hdGNoOgogICAgICBtYWNhZGRyZXNzOiAiYWE6ZmY6MDA6MDA6MDA6MDEiCiAgICBhZGRyZXNzZXM6CiAgICAgIC0gMTcyLjE2LjAuMgo=' |base64 -d
version: 2
ethernets:
  eth0:
    match:
      macaddress: "aa:ff:00:00:00:01"
    addresses:
      - 172.16.0.2
```

The question really is why is the kernel cmdline shown by `/proc/cmdline` not being found by cloud-init?  

To give you a reproducer of our exact environment we would have to give you the kernel, and root filesystem, images that were created using Docker - this is a Firecracker VM.  The vm is started with a NIC with the mac address above, small disk, and the kernel cmdline as supplied.

The Docker images are built from `FROM ubuntu:20.04` or `FROM ubuntu:22.04`.  Using the 20.04 image, the network config is read perfectly.  When we switch to 22.04, making no other change, the network config is not read.
