### ISSUE TITLE
Duplicate mac found with (ovs) bridge

### ISSUE THREAD

**Issue by fwiesel** [canonical/cloud-init#5810]
# Bug report
Similar to #3316. If I create an ovs bridge and add the interface to the bridge, the bridge will also have the mac-address of the underlying interface (in my case a bond)

## Steps to reproduce the problem
/etc/netplan/50-cloud-init.yaml:
```yaml
network:
  bonds:
    bond0:
      interfaces
      - enp1..
      - enp2...
      macaddress: mac1
  bridges:
    br-ex:
      dhcp4: true
      interfaces:
     - bond0
     openvswitch: {}
  ethernets:
    enp1:
      match:
         macaddress: mac1
      set-name: enp1
    enp2:
      match:
         macaddress: mac2
      set-name: enp2
  openvswitch: {}
  version: 2
  vlans: {}
```

## Environment details
- Cloud-init version: 24.3.1
- Operating System Distribution: Gardenlinux (Essentially Debian Trixie)
- Cloud provider, platform or installer type: Openstack Nova / Ironic on Baremetal

## cloud-init logs

Backtrace is manually copied, as I have no network connectivity:
```
sources/DataSourceConfigDrive.py:173 (network_config)
sources/helpers/openstack.py:760 (convert_net_json)
net/__init__.py:891 (get_interfaces_by_mac)
net/__init__.py:990 (get_interfaces_by_mac_on_linux)
```
