### ISSUE TITLE
[enhancement]: ds-identify dscheck_None should run check_config

### ISSUE THREAD

**Issue by chen23** [canonical/cloud-init#5821]
# Enhancement

Currently it is documented that None can be configured via a datasource:

https://cloudinit.readthedocs.io/en/latest/reference/datasources/none.html
```
datasource:
  None:
    metadata:
      local-hostname: "myhost.internal"
    userdata_raw: |
      #cloud-config
      runcmd:
      - echo 'mydata' > /var/tmp/mydata.txt
```
The "default" setting of ds-identify will ignore any configuration for None unless there are no datasources or it is the only one: 
```
dscheck_None() {
    return ${DS_NOT_FOUND}
}
```
it would be nice if it checked the config
```
    if check_config "None"; then
        if check_config "userdata_raw" && check_config "metadata"; then
            return ${DS_FOUND}
        fi
    fi
```
This would also address of the issue of how to always run cloud-init when no datasource is found (by explicitly adding a config for None in the config) [#3772#issuecomment-1545394489](https://github.com/canonical/cloud-init/issues/3772#issuecomment-1545394489)
