### ISSUE TITLE
network v2 schema too permissive

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/cloud-init#5854]
With netplan uninstalled, given a config like:
```
network:
  version: 2
  ethernets:
    eth0:
      somekey: somevalue
```

Running `cloud-init schema --system` yields
```
Found cloud-config data types: user-data, network-config

1. user-data at /var/lib/cloud/instances/a1747431-4e15-4388-80b5-a32ccaeeaaa0/cloud-config.txt:
  Valid schema user-data

2. network-config at /var/lib/cloud/instances/a1747431-4e15-4388-80b5-a32ccaeeaaa0/network-config.json:
  Valid schema network-config
```

even though we should see a warning about `somekey` being invalid.
