### ISSUE TITLE
[enhancement]: Allow configuring pin-priorities

### ISSUE THREAD

**Issue by adam-vest** [canonical/cloud-init#5862]
# Enhancement

Hi there!

At present, I don't believe there is a built-in way to configure pin priorities in `/etc/apt/preferences.d` via cloud-init. This can be accomplished currently by just `write_files`, but it might be a nice-to-have feature to support this natively. Maybe just as a key under `apt`, like:
```
apt:
  preferences:
    my-pref:
      Package: *
      Pin: release o=SomeOrigin
      Pin-Priority: 1001
```

Thank you!
