### ISSUE TITLE
[docs]: Questions About Route Configuration

### ISSUE THREAD

**Issue by xiaoge1001** [canonical/cloud-init#5940]
# Documentation request

I use the following routing configuration:
https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v1.html#route-example

dev name and mac_address match the one in my environment, not the one in the example.  However, the route in the example cannot be queried.
![image](https://github.com/user-attachments/assets/c7302b64-a808-44ae-8933-2ba21082d03e)

I get 192.168.23.0/24, not 192.168.24.0/24. Why is that?

**Comment by dermotbradley** [comment]
That example would only work if the route was added as an "onlink" route (a "normal" route requires the gateway to have an IP address in the machine's subnet).

Which distro, which cloud-init version, and which cloud-init network renderer are you using?

Only the netplan and networkd renderers appear to support "onlink".

**Comment by xiaoge1001** [comment]
> That example would only work if the route was added as an "onlink" route (a "normal" route requires the gateway to have an IP address in the machine's subnet).
> 
> Which distro, which cloud-init version, and which cloud-init network renderer are you using?
> 
> Only the netplan and networkd renderers appear to support "onlink".

I get it，Thanks

distro: openEuler
cloud-init version:23.4.1
cloud-init network renderer:sysconfig

**Comment by xiaoge1001** [comment]
https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v1.html#nameserver-example
```
network:
  version: 1
  config:
    - type: physical
      name: interface0
      mac_address: '00:11:22:33:44:55'
      subnets:
         - type: static
           address: 192.168.23.14/27
           gateway: 192.168.23.1
    - type: nameserver
      interface: interface0  # Ties nameserver to interface0 only
      address:
        - 192.168.23.2
        - 8.8.8.8
      search:
        - exemplary
```

Is this supported by some network renderers? I test it and the cloud-init command is successfully executed, but the nameserver information cannot be found.
