### ISSUE TITLE
LibVIRT example not working

### ISSUE THREAD

**Issue by aladrocMatiner** [canonical/cloud-init#5960]
I tested this from documentation and is not working

https://cloudinit.readthedocs.io/en/latest/howto/launch_libvirt.html#

The system as a Debian 12, the vm started but never executed the cloud init scripts

**Comment by shaerpour** [comment]
> I tested this from documentation and is not working
> 
> https://cloudinit.readthedocs.io/en/latest/howto/launch_libvirt.html#
> 
> The system as a Debian 12, the vm started but never executed the cloud init scripts

Dear @aladrocMatiner 

Do you have same problem with Ubuntu images like jammy?

As an example, I use below configurations for ansible module (jammy image):

1- Your Cloud config (for example ansible module):
```yaml
#cloud-config
password: password
chpasswd:
  expire: False
ansible:
  install_method: distro
  package_name: ansible-core
  pull:
    url: https://github.com/holmanb/vmboot.git
    playbook_name: ubuntu.yml
```

2- virt-install
```bash
sudo virt-install --name x --memory 1024 --noreboot --os-variant detect=on,name=ubuntujammy --disk=size=10,backing_store="srv.img" --cloud-init user-data="$(pwd)/user-data,meta-data=$(pwd)/meta-data,network-config=$(pwd)/network-config"
```
