### ISSUE TITLE
Can not override distro default user

### ISSUE THREAD

**Issue by ElSamhaa** [canonical/cloud-init#5981]
# Bug report
According to the [docs](https://cloudinit.readthedocs.io/en/23.4/reference/modules.html#users-and-groups), the default user data can be overriden by the `user` dictionary keys. Unfortunately, this is not the case.

## Steps to reproduce the problem
Apply the below user_data to Almalinux 9.5 generic cloud image
```yaml
#cloud-config

user:
  name: samha
  plain_text_passwd: password
  lock_passwd: false

users:
- name: root
  plain_text_passwd: password
  lock_passwd: false
```
The `root` password is modified but the default user (i.e `almalinux`) is not changed to `samha`.

## Environment details
- Cloud-init version: 23.4
- Operating System Distribution: Almalinux
- Cloud provider, platform or installer type: KVM

## cloud-init logs

[cloud-init.tar.gz](https://github.com/user-attachments/files/18454813/cloud-init.tar.gz)
