### ISSUE TITLE
[docs]: groups only works if given as list

### ISSUE THREAD

**Issue by jepper** [canonical/cloud-init#6108]
# Documentation request

Using a list works, wheel group is populated:
```
users:
  - name: myuser
    groups:
      - wheel
```

does not work, wheel group is empty:
```
users:
  - name: myused
    groups: wheel
```

---
*Reported from: https://cloudinit.readthedocs.io/en/latest/reference/yaml_examples/user_groups.html*
