### ISSUE TITLE
Specific inputs cause netplan generation to fail when deferring to netplan parser/state

### ISSUE THREAD

**Issue by akutz** [canonical/cloud-init#6239]
# Bug report
Beginning with #4981 (since Cloud-Init release [24.2-0ubuntu1_23.10.1](https://github.com/canonical/cloud-init/releases/tag/24.2-0ubuntu1_23.10.1)), netplan generation fails on specific inputs when the native netplan parser/state Python bindings are used.

## Steps to reproduce the problem
The issue is fully documented, including steps to reproduce, at https://github.com/canonical/cloud-init/compare/main...akutz:cloud-init:mtu. The tl;dr is:

* Given the following network v2 configuration:

    ```yaml
    network:
      version: 2
      ethernets:
        eth0:
          match:
            macaddress: "00:11:22:33:44:55"
          nameservers:
            addresses:
            - 8.8.8.8
            search:
            - spam.local
            - eggs.local
          mtu: 0
    ```

* Cloud-init fails at https://github.com/canonical/cloud-init/blob/4512e9e3c710199d0a8b4b4a24f069ec4f352006/cloudinit/net/netplan.py#L390 (or whenever `netplan generate` is executed due to https://github.com/canonical/cloud-init/blob/4512e9e3c710199d0a8b4b4a24f069ec4f352006/cloudinit/net/netplan.py#L268-L284 generating a file that looks like this:

    ```yaml
    network:
      version: 2
      ethernets:
        eth0:
          match:
            macaddress: "00:11:22:33:44:55"
          nameservers:
            addresses:
            - 8.8.8.8
            search:
            - spam.local
            - eggs.local
          mtu: null
    ```

* Then, when netplan tries to parse the file, it will produce the following error:

    ```shell
    $ netplan generate
    /etc/netplan/50-cloud-init.yaml:13:12: Error in network definition: invalid unsigned int value 'null'
          mtu: null
    ```

It may be the case that `ethernets[].mtu` should be a positive integer, but sending it as zero always worked in the past, and now it causes the entire bootstrap process to fail. To me this is a breaking, behavioral change that should be either reverted or handled internally in Cloud-Init to strip out the `0`.

## Environment details
Not needed

## cloud-init logs
Not needed
